### ISSUE TITLE
distDir and withCSS do not work

### ISSUE THREAD

**Issue by shprink** [zeit/next-plugins#103]
When using `distDir` in next.config.js `<link rel="stylesheet" href="/_next/static/style.css" />` is 500.   in my setup: `distDir: '../functions/.next',` (using with firebase functions)

![image](https://user-images.githubusercontent.com/1388706/37455962-9db70690-283e-11e8-8fdb-9d3b7d4a3ac0.png)

When removing `distDir` it works as expected:

![image](https://user-images.githubusercontent.com/1388706/37456104-ebc0f634-283e-11e8-876b-9549829b4622.png)

**Comment by kachkaev** [comment]
@shprink try next@canary – this should be fixed there.

**Comment by shprink** [comment]
Confirmed. `yarn upgrade next@canary` fixes the problem.

Thanks very much
