### ISSUE TITLE
How do you include vendor css?

### ISSUE THREAD

**Issue by genetrybeai** [zeit/next-plugins#110]
I want to include the [react-select](https://github.com/JedWatson/react-select) component in my project.  I have the component installed in node_modules.

But the component is rendering without style.  How do I include the css dependency [react-select.css](https://github.com/JedWatson/react-select/blob/master/dist/react-select.css) in my project?

**Comment by Ehesp** [comment]
Simply import it:

```
import 'react-select/dist/react-select.css';
```

**Comment by genetrybeai** [comment]
That doesn't appear to work.  Some documentation with a known example would be greatly appreciated.

**Comment by kamui** [comment]
I have the same issue. The problem is turning on css modules, it treats all vendor css as local css modules, not global.

**Comment by paintedbicycle** [comment]
Is there any information on this?

There is #151 but it was closed as duplicate of #322 but #322 doesn't seem to be getting merged.

How can I include a SCSS file, in a component, where that component references a vendor component. I can't pass the styles to the vendor component.
