### ISSUE TITLE
next css plugin with "css module configuration" does not work since the 0.1.0 version

### ISSUE THREAD

**Issue by jeco123** [zeit/next-plugins#113]
next css plugin with css module does not work since 0.1.0

create-next-app --example with-next-css with-next-css-app 
version used: "@zeit/next-css": "0.0.7" => OK

The same exemple with the version @zeit/next-css": "0.1.4" KO

**Comment by timneutkens** [comment]
Please provide a repository to reproduce. Also try `next@canary` with the latest version of next-css.

**Comment by jeco123** [comment]
just replay this scenraio at https://github.com/zeit/next.js/tree/canary/examples/with-next-css and change the next-css package version to 0.1.4.

**Comment by timneutkens** [comment]
I can't reproduce the issue:

`create-next-app --example with-next-css with-next-css-app`

`cd with-next-css`

`yarn add @zeit/next-css@latest`

`yarn dev`

Shows styled page.

**Comment by jeco123** [comment]
@timneutkens sorry i forgot to precise that it should be configured With CSS Modules. Go to next.config.js and uncomment.

**Comment by timneutkens** [comment]
Still works, tested it too, don't forget to update `pages/index.js` to use the scoped styles.

```
import css from '../style.css'

export default () => <div className={css.example}></div>
```

**Comment by jeco123** [comment]
ok i understand my pb. the _document.js file was removed.
