### ISSUE TITLE
next-css duplicates styled-components style definitions

### ISSUE THREAD

**Issue by dargue3** [zeit/next-plugins#115]
Not entirely sure which repo to report this issue to, I picked this one because it's the newest 🙂

When using styled-components and next-css, your `_document.js` looks something like the following:

```javascript
import Document, { Head, Main, NextScript } from 'next/document';
import { ServerStyleSheet } from 'styled-components';

export default class _Document extends Document {
  static getInitialProps({ renderPage }) {
    const sheet = new ServerStyleSheet();
    const page = renderPage(App => props => sheet.collectStyles(<App {...props} />));
    const styles = sheet.getStyleElement();
    return { ...page, styles };
  }

  render() {
    return (
      <html lang="en">
        <Head>
          <meta charSet="utf-8" />
          <link rel="stylesheet" href="/_next/static/style.css" />
          {this.props.styles}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

But I soon noticed that I was getting duplicate class declarations inside `<head>` upon server load.

![image](https://user-images.githubusercontent.com/13652794/37849135-c894e296-2e93-11e8-8b2b-d633972d81c9.png)

I found that removing the `{this.props.styles}` line from inside `<Head>` fixed the issue. Should note however that your `getInitialProps` still needs to return the `styles` variable, otherwise you get a FOUC.

Is this a bug or is a ✨Feature ✨ that next-css seems to be scooping up the styled-components declarations?

**Comment by timneutkens** [comment]
Fun story:

Yes it's a feature, and it's a bug in your code, if `styles` is returned in `getInitialProps` they get rendered automatically by Next, eg the parent `getInitialprops` return the result of styled-jsx as `styles`. As you can see the styled-jsx example uses `styleTags` as variable. Both work and there's not much different.

https://github.com/zeit/next.js/blob/canary/examples/with-styled-components/pages/_document.js#L17

It's unrelated to next-css/css imports 👍
