### ISSUE TITLE
main.js sourcemap not copied when running export

### ISSUE THREAD

**Issue by robinvdvleuten** [zeit/next-plugins#122]
When I export my Next.js project as a static website, the main.js sourcemap isn't included. The sourcemap plugin is included in my `next.config.js` file.

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next.js/pull/4639

**Comment by robinvdvleuten** [comment]
Thanks @timneutkens!

**Comment by timneutkens** [comment]
All client files are now served from `.next/static` which is copied as a whole into `out/_next/static` so we got this issue fixed for free 😄
