### ISSUE TITLE
Less 3 not working due to inline javascript.

### ISSUE THREAD

**Issue by jamieowen** [zeit/next-plugins#123]
Hey,

Great work on this.
Took me a while to get it working with antd but got there in the end.

I couldn't get the next-less plugin working with latest less.

I had to install @2.7.3

I did however clone this repo and fixed the problem by modifying the less-loader entry to include 
```
{
    loader: 'less-loader',
    options: {
        javascriptEnabled: true
    }
}
```
Perhaps along with the cssLoaderOptions, there was a lessLoaderOptions property.

```
// next.config.js
const withLess = require('@zeit/next-less')
module.exports = withLess({
  cssModules: true,
  lessLoaderOptions: {
     javascriptEnabled: true
  }
})
```

Cheers

**Comment by rmarscher** [comment]
#124

**Comment by CrisLi** [comment]
We also need less loader options. The pull request has been sent for a while, no one approves it.
