### ISSUE TITLE
Use next-sass to import scss as css string and put in styled jsx tag

### ISSUE THREAD

**Issue by verzola** [zeit/next-plugins#126]
Is it possible to put the style in styled jsx tag with next-sass plugin? I could not find a example anywhere.
I got it working with this example, but it uses custom webpack config and dangerouslySetInnerHTML: https://github.com/zeit/next.js/tree/master/examples/with-global-stylesheet

```js
import React from 'react'
import stylesheet from 'styles/index.scss'

export default () =>
  <div>
    <style dangerouslySetInnerHTML={{ __html: stylesheet }} />
    <p>ciao</p>
  </div>
```

**Comment by timneutkens** [comment]
Will be supported in styled-jsx v3 https://github.com/zeit/styled-jsx/pull/422

**Comment by verzola** [comment]
Thanks for the reply! Nice work with NextJS. It is being very pleasuring to use it.

**Comment by timneutkens** [comment]
Glad you like it 😌☺️
