### ISSUE TITLE
How to import sass with css modules AND without?

### ISSUE THREAD

**Issue by morgs32** [zeit/next-plugins#135]
I'd like to import this `global.styles.scss` file in every page
```

/**
  Bootstrap
 */
@import "~bootstrap/scss/reboot";
@import "~bootstrap/scss/type";
@import "~bootstrap/scss/grid";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/tables";
@import "~bootstrap/scss/media";
@import "~bootstrap/scss/utilities/align";
@import "~bootstrap/scss/utilities/flex";
@import "~bootstrap/scss/utilities/display";
@import "~bootstrap/scss/utilities/spacing";
@import "~bootstrap/scss/utilities/sizing";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/transitions";
@import "~bootstrap/scss/_buttons.scss";
@import "~bootstrap/scss/_dropdown.scss";
@import "~bootstrap/scss/_card.scss";
@import "~bootstrap/scss/_nav.scss";
```

And theme bootstrap while I'm at it.

But also I'd like to use CSS modules in my components.

If I try to wrap the above imports in `:global`, it doesn't work. 

```
ModuleBuildError: Module build failed: ModuleBuildError: Module build failed: Missing whitespace before :global (3014:5)

  3012 |       background-color: #007bff;
  3013 |       border-color: #007bff; }
> 3014 |     :global .btn-primary:not(:disabled):not(.disabled):active, :global .btn-primary:not(:disabled):not(.disabled).active,
       |     ^
  3015 |     .show > :global .btn-primary.dropdown-toggle {
  3016 |       color: #fff;
  3017 |       background-color: #0062cc;

```

**Comment by mgiraldo** [comment]
i'm in a similar situation where i want SASS _with_ modules and also have some global CSS files/rules that I don't want affected by the modular behavior. is this possible without having to put the global files in `/static`?

**Comment by Asher978** [comment]
I am in a similar situation as well. None of the docs that are provided (here)[https://github.com/zeit/next-plugins/tree/master/packages/next-sass] work. 

This has to be resolved or please provide an update !

**Comment by lailo-ch** [comment]
Did anyone find a solution for this?

**Comment by dgollub** [comment]
We are running into this issue as well (only we use react-md instead of bootstrap). Is there any solution besides adding an extra build step to generate the global CSS file from the react-md SCSS sources?

**Comment by fatlinesofcode** [comment]
you as custom **getLocalIdent** function to stop rewriting classnames in files named *global

e.g.

```
module.exports = withCSS(withSass({
  cssModules: true,
cssLoaderOptions: {
    // localIdentName: "[name]__[local]",
    getLocalIdent: (loaderContext, localIdentName, localName, options) => {
      const fileName = path.basename(loaderContext.resourcePath)
      if(fileName.indexOf('global.scss') !== -1){
        return localName
      }else{
        const name = fileName.replace(/\.[^/.]+$/, "")
        return `${name}__${localName}`
      }
    }
  },
}))
```

**Comment by astenmies** [comment]
based on @fatlinesofcode code here's some extra fine-tuning if required. So stylesheets that are at component levels can use css modules while the ones from avoidPaths array will not be transformed.

```js
const avoidPaths = ['src/styles/css-new', 'node_modules', 'src/pages']
	.map(d => path.join(__dirname, d))
	.map(g => glob.sync(g))
	.reduce((a, c) => a.concat(c), []);

function canBeTransformed(pathToCheck) {
	if (avoidPaths.some(function(v) {
		return pathToCheck.indexOf(v) >= 0;
	})) {
		return false;
	} else {
		return true;
	}
}

module.exports = withSass({
    cssModules: true,
    cssLoaderOptions: {
        // localIdentName: "[name]__[local]",
        getLocalIdent: (loaderContext, localIdentName, localName, options) => {
        const fileName = path.basename(loaderContext.resourcePath)
        if(!canBeTransformed(loaderContext.resourcePath)){
            return localName
        }else{
            const name = fileName.replace(/\.[^/.]+$/, "")
            return `${name}__${localName}`
        }
        }
    },
})
```

**Comment by astenmies** [comment]
Some fine-tuning based on fatlinesofcode's answer...

- in `src/comps` -> not transformed unless suffix is _module
- in `avoidPaths` -> never transformed

```js
const avoidPaths = ['src/styles/css-new', 'node_modules', 'src/pages'].map(d => path.join(__dirname, d));

function canBeTransformed(pathToCheck) {
	return !avoidPaths.some(function(v) {
		const path = pathToCheck.substr(0, pathToCheck.lastIndexOf('/') + 1);
		return v.includes(path);
	});
}

// prettier-ignore
module.exports = withSass({
    cssModules: true,
    cssLoaderOptions: {
        getLocalIdent: (loaderContext, localIdentName, localName, options) => {
            const fileName = path.basename(loaderContext.resourcePath)
            const shoudTransform = canBeTransformed(loaderContext.resourcePath)

            if(!shoudTransform){
                return localName
            }else{
                const name = fileName.replace(/\.[^/.]+$/, "")
                const suffix = name.substring(name.lastIndexOf("_") + 1);
                if(suffix === "module") {
                    return `${name}___${localName}`
                } else {
                    return localName
                }
            }
        }
    },
})
```

**Comment by affanshahid** [comment]
Thanks @astenmies  and @fatlinesofcode. Solution works, just wondering if it is possible to use the default mangled names that are generated by default for files that don't match.

i.e `ftuojk123` instead of `login___loginBox`

**Comment by yeluoqiuzhi** [comment]
@affanshahid Only work when import bootstrap.scss in js file, it will failed when import in scss file like this:
```scss
@import '~bootstrap/scss/bootstrap.scss';
```

**Comment by huycuongdao** [comment]
> @affanshahid Only work when import bootstrap.scss in js file, it will failed when import in scss file like this:
> 
> ```scss
> @import '~bootstrap/scss/bootstrap.scss';
> ```

@yeluoqiuzhi  You should include this:
```
sassLoaderOptions: {
  includePaths: ["node_modules", "./node_modules"],
},
```
in your `next.config.js` file. It works for me.

**Comment by cedeber** [comment]
I end up using CSS for global and SCSS for modules.

Current config is:
```js
const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");

module.exports = withSass({
    ...withCSS({ cssModules: false }),
    cssModules: true
});
```

while global.css is
```css
@import "~normalize.css/normalize.css";
@import "~@blueprintjs/core/lib/css/blueprint.css";
@import "~bootstrap/dist/css/bootstrap-grid.css";
```
imported as `import ./global.css`

For the SCSS modules files you can do it as usual with `import style from "./file.scss"`

**Comment by cedeber** [comment]
But I have a problem. The SCSS modules are always written before the global styles in the generated css on build. This is the contrary with dev, which is what is desired because you want to overwrite global style. This is confusing and boring because it is unreliable.

**Comment by zposten** [comment]
> > @affanshahid Only work when import bootstrap.scss in js file, it will failed when import in scss file like this:
> > ```css-scss
> > @import '~bootstrap/scss/bootstrap.scss';
> > ```
> 
> @yeluoqiuzhi You should include this:
> 
> ```
> sassLoaderOptions: {
>   includePaths: ["node_modules", "./node_modules"],
> },
> ```
> 
> in your `next.config.js` file. It works for me.

@huycuongdao I believe the reason that @affanshahid 's solution did not work for @yeluoqiuzhi was because the `loaderContext.resourcePath` is always (for me at least) the name of the SCSS file that was imported by the JavaScript.  It is never the name of an SCSS file that is imported by another SCSS file.

Because of that, I don't understand how @affanshahid's solution works.  @fatlinesofcode's solution works because it's checking for the name of the single global SCSS file that is imported by JavaScript, and not for the names of the files which that file imports.

```
Next.js v9.1.4
@zeit/next-sass v1.0.1
css-loader v3.2.0
sass-loader v6.0.6
```

**Comment by lucatk** [comment]
@zposten 
This seems to be the solution! Many thanks. Using css-loader@3.3.0 however, it seems they removed the export of getLocalIdent (at least I couldn't manage to import it).
However, I just copied the relevant bits out, modified the imports to make it work, and moved it to next.config.js.
Here's my modified next.config.js: (the helper could also be put into another file)
```js
const withSass = require('@zeit/next-sass');

module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[local]___[hash:base64:5]',
    // allow both CSS modules AND global stylesheets (https://github.com/zeit/next-plugins/issues/135#issuecomment-563415934)
    getLocalIdent: (loaderContext, localIdentName, localName, options) => {
      let filePath = loaderContext.resourcePath;
      let isFromGlobal = filePath.includes('global.scss');
      if (isFromGlobal) return localName;

      return defaultGetLocalIdent(
        loaderContext,
        localIdentName,
        localName,
        options
      );
    }
  }
});

// hijacked from css-loader/dist/utils and slightly modified...
const _path = require("path");
const _loaderUtils = require("loader-utils");
const _normalizePath = require("normalize-path");
const _cssesc = require("cssesc");
const filenameReservedRegex = /[<>:"/\\|?*\x00-\x1F]/g; // eslint-disable-next-line no-control-regex
const reControlChars = /[\u0000-\u001f\u0080-\u009f]/g;
const reRelativePath = /^\.+/;
const defaultGetLocalIdent = (loaderContext, localIdentName, localName, options) => {
  if (!options.context) {
    // eslint-disable-next-line no-param-reassign
    options.context = loaderContext.rootContext;
  }

  const request = (0, _normalizePath)(_path.relative(options.context || '', loaderContext.resourcePath)); // eslint-disable-next-line no-param-reassign

  options.content = `${options.hashPrefix + request}+${unescape(localName)}`; // Using `[path]` placeholder outputs `/` we need escape their
  // Also directories can contains invalid characters for css we need escape their too

  return (0, _cssesc)(_loaderUtils.interpolateName(loaderContext, localIdentName, options) // For `[hash]` placeholder
  .replace(/^((-?[0-9])|--)/, '_$1').replace(filenameReservedRegex, '-').replace(reControlChars, '-').replace(reRelativePath, '-').replace(/\./g, '-'), {
    isIdentifier: true
  }).replace(/\\\[local\\\]/gi, localName);
};
```

**Comment by morgs32** [comment]
Solved? Closing.
