### ISSUE TITLE
next-css - import external CSS and use embedded fonts and images.

### ISSUE THREAD

**Issue by asicfr** [zeit/next-plugins#139]
Hello, i try to use an external CSS with next-css.  
All stylesheets are compiled to ".next/static/style.css", 
but fonts files : 
`@font-face {
    font-family: "Avenir";
    src: url("#{$font-path}avenir-book.woff") format("woff");
}`
and images files : 
`background-image: url("paper.gif")`
are lost (no woff or png file in the directory ".next/static/").

I used the following configuration in "next.config.js" : 
```
   // Inject CSS with css-loader used within next-css plugin  
    config.module.rules.push({  
      test: /\.css$/,  
      use: ['style-loader', 'css-loader', 'postcss-loader'],  
      include: ['node_modules/test-styleguide']  
    }, {  
        test: /\.(png|woff|woff2|eot|ttf|svg|gif|jpg)$/,  
        loader: 'file-loader',  
        options: {  
          publicPath: '/'  
        }  
      },  
      {  
        test: /\.(png|woff|woff2|eot|ttf|svg|gif|jpg)$/,  
        loader: 'url-loader?limit=10000'  
      });  
```  

The solution with "postcss.config.js" and url: 'inline' works but i don't want to inline all fonts and images files for performance reason.

Have you any clue to resolve that problem ?
Thx

My Environment : 
"next": "5.0.0"
"@zeit/next-css": "0.1.5"
"css-loader": "0.28.11"
"url-loader": "0.5.8"
"postcss-loader": "2.1.3"

**Comment by timneutkens** [comment]
You can do something like https://github.com/arefaslani/next-images/blob/master/index.js
