### ISSUE TITLE
Continuation of the issue 139

### ISSUE THREAD

**Issue by asicfr** [zeit/next-plugins#141]
[issues 139](https://github.com/zeit/next-plugins/issues/139)
Thx @timneutkens  but it not works ... no woff file in .next directory
To clarify : it's an external stylesheets, ie. the css file, woff and images are in a node_module.
The css file references assets using a relative path :
@font-face{font-family:"Avenir";font-weight:200;src:url("./fonts/avenir-lighter.woff")
I think that the imports and url(...)s in the CSS are not resolve with the CSS loader.

**Comment by timneutkens** [comment]
css loader does not resolve imports. So it's up to you to implement it. In the other issue I meant you could take next-images as an example to implement your own.

Adding loaders for fonts etc is out of scope for next-css / sass / less, they just implement the corresponding webpack loader.

**Comment by asicfr** [comment]
Ah, i found : https://github.com/zeit/next.js/pull/4015
So pass to 5.1.0 and it works !!!
