### ISSUE TITLE
Accessing sass variables declared in sass files within styled-jsx

### ISSUE THREAD

**Issue by JonAbrams** [zeit/next-plugins#146]
Let's say I have a file called `_colors.scss` that define a bunch of color variables, e.g. `$primary-color: blue`, and it's being imported and compiled using `@zeit/next-sass`, then served up at `_next/static/style.css`. Those are used heavily in my global/common sass/scss files, but they don't seem to be accessible from styled-jsx blocks. Is there a way to do that?

Thanks for all the great work!

**Comment by timneutkens** [comment]
No there is no way to interleave next-sass and styled-jsx at this moment.
