### ISSUE TITLE
How do you enable inline javascript in next-less

### ISSUE THREAD

**Issue by krokhale** [zeit/next-plugins#147]
While compiling the less files, i come across this error

    Inline JavaScript is not enabled. Is it set in your options?

How do i pass in options to the less compiler in next-less?

**Comment by danielmichaelni** [comment]
How were you able to resolve this?

**Comment by simonyouth** [comment]
```js
module.exports = withLess({
    lessLoaderOptions: {
        javascriptEnabled: true,
    },
})
```
