### ISSUE TITLE
Confusing readme in next-bundle-analyzer

### ISSUE THREAD

**Issue by tim-phillips** [zeit/next-plugins#161]
1) In the [next-bundle-analyzer](https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer) plugin's readme, we import `BundleAnalyzerPlugin` from `webpack-bundle-analyzer` but don't actually use it. Should this be removed?

2) It says "make sure you have next-css set up", although I don't see any mention of it in the config example.

3) I'm trying to see the gain in using this plugin over just following the [example](https://github.com/zeit/next.js/blob/canary/examples/with-webpack-bundle-analyzer/next.config.js). The example seems simpler! Let me know what I'm missing.

**Comment by kachkaev** [comment]
The above issues seem to be resolved (https://github.com/zeit/next.js/tree/canary/packages/next-bundle-analyzer). Besides, the plugin is now marked as deprecated and has been moved to [@next/bundle-analyzer](https://github.com/zeit/next.js/tree/canary/packages/next-bundle-analyzer). @tim-phillips WDYT?
