### ISSUE TITLE
next-typescript 1.0 not working correctly

### ISSUE THREAD

**Issue by wereHamster** [zeit/next-plugins#173]
With next 6.0.1 and next-typescript 1.0.0 installed, create this page:

```
interface CrashMe {}
export default () => null
```

And when you try to open it in the browser you'll get:

```
Error in ./pages/index.tsx
Module build failed: SyntaxError: …/pages/index.tsx: interface is a reserved word in strict mode (1:0)

> 1 | interface CrashMe {}
    | ^
  2 | export default () => null
```

This was working with next-typescript 0.x.

**Comment by timneutkens** [comment]
I can't reproduce this. I'm thinking you forgot to add the new babel preset: https://github.com/zeit/next-plugins/tree/master/packages/next-typescript#usage
