### ISSUE TITLE
Unexpected token with next-typescript

### ISSUE THREAD

**Issue by matteoantoci** [zeit/next-plugins#174]
Since I upgraded `next-typescript` to version `1.0.0` I'm getting an `Unexpect token` error when building.

I'm not using a custom babel config and everything worked pretty well with `0.1.1`. I had to rollback the version and now everything is working fine as before.

FYI this is my next config:

```
const withTypescript = require('@zeit/next-typescript');
const withCSS = require('@zeit/next-css');

module.exports = withTypescript(withCSS());

**Comment by timneutkens** [comment]
Sounds like a duplicate of #173 
Follow the installation instruction:
https://github.com/zeit/next-plugins/tree/master/packages/next-typescript#usage

**Comment by matteoantoci** [comment]
@timneutkens Thanks! I needed to setup a the `.babelrc`. Just curious, why switching to babel?
