### ISSUE TITLE
next-css and extract-text-webpack-plugin incompatible with Webpack 4

### ISSUE THREAD

**Issue by LockeAG** [zeit/next-plugins#182]
based in what the team behind Extract-Text-Webpack-Plugin says.

we should be moving to: [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin)

`Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead.`

is there any plan to move to Webpack4?

well, until Webpack 5 comes out (seems that a CSS minimizer will be built-in )

**Comment by timneutkens** [comment]
Next.js doesn't support webpack 4 at the moment. There's an issue for it on the Next.js repository.

**Comment by albinekb** [comment]
@timneutkens now that next supports webpack 4, should we update `@zeit/next-css` to use *mini-css-extract-plugin* instead?

**Comment by timneutkens** [comment]
Funny you're asking that:

<img width="562" alt="screen shot 2018-07-28 at 19 59 25" src="https://user-images.githubusercontent.com/6324199/43359317-c47de61e-92a0-11e8-8e25-182a8f1b01d3.png">

Was trying that out today

**Comment by 40x** [comment]
Any update on this? Would be nice to have `extract-text-webpack-plugin` to point to `^4.0.0-beta.0`

**Comment by timneutkens** [comment]
`extract-text-webpack-plugin` is deprecated on `webpack@4`. `@zeit/next-css@canary` uses `mini-css-extract-plugin`
