### ISSUE TITLE
Styles not loaded.

### ISSUE THREAD

**Issue by loconluis** [zeit/next-plugins#187]
Im using Next Js 6.0.x

When Im in Dev Mode my Stiles are loaded fine (im using sass)

But when I create a Build, Styles doest loaded, someone knows something about that??

**Comment by jakeleboeuf** [comment]
I'm having the same issue, but using Postcss.

**Comment by alexlapinski** [comment]
@jakeleboeuf the fix for plain css seemed to be to move the import to the page level, and not in the _document file, maybe this will work for postcss as well?

**Comment by aequasi** [comment]
make sure you update `@zeit/next-sass` and `@zeit/next-css` to `0.2.0`, solves this issue

**Comment by and3rsonsousa** [comment]
None of the solutions worked for me. I got the problem when I use "node server.js". The style.css file is not created, only using in dev mode "next". I am also using sass.

**Comment by Ionut-Milas** [comment]
Any updates on this one? I have the same issue ? @and3rsonsousa

**Comment by markolofsen** [comment]
Same issue

**Comment by markolofsen** [comment]
**npm ls @zeit/next-sass**
`└── @zeit/next-sass@0.2.0`

**npm ls @zeit/next-css**
```
├── @zeit/next-css@0.2.0
└─┬ @zeit/next-sass@0.2.0
  └── @zeit/next-css@0.2.0  deduped
```

**Comment by webtjw** [comment]
@markolofsen @aequasi 
I have the same issue too. But I soon found that the reason of styles not loading while using react routing  in dev mode, might be using multi type of css languages. In my case I used sass and css in the same `_document.js`. Problem was saolved when I only use sass.

I think the config might be related to the problem. Here's my config in `next.config.js`:

```
const withCSS = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const commonsChunkConfig = require('@zeit/next-css/commons-chunk-config')

const config = withCSS(withSass({
  webpack: (config, {isServer}) => {
    if (!isServer) {
      config = commonsChunkConfig(config, /\.(sass|scss|css)$/)
    }
    return config
  }
}))

module.exports =  config
```
