### ISSUE TITLE
Sass partials source mapping

### ISSUE THREAD

**Issue by aurelienbobenrieth** [zeit/next-plugins#188]
Hello everybody, 

It's been some hours I've been stuck on a problem so I felt like posting my issue here looking for some help.

Here is my problem, I am trying to use Chrome DevTools source mapping for my stylesheet.
I am using @zeit/next-sass.

I can't seem to find the proper way to use Chrome DevTools to source map my .scss partials files. In the console the properties lines are all directing to my compiled main.scss file.

Also when I try to modify my scss file there is no persistence in what I do in my chrome console.

I did try a lot of differents tutos, doing some sass --watch, adding   devtool: 'inline-source-map, and so on, but nothing seems to work.

I must be doing something wrong. Would anyone be gentle enough to help me doing the proper stuff to make that work. That would improve my workflow speed so much !

Kind regards community ! 

EDIT : I now found a way to get my scss in my devtools with the right path to partials by replacing : 
`<link rel="stylesheet" href="/_next/static/style.css" />`
by
`<link rel="stylesheet" href="/static/scss/main.css" /> (genetared by sass gem)`

The problem is that if I want my changes to be persistent I need to do them in the sources panel. I can't just modify css properties in the classic properties panel. This is problematic because if I do change the properties in the sources panel I can't benefit of the live reload which is a bit of a time waste.

**Comment by ruslansavenok** [comment]
@aurelienbobenrieth following config works for me.

```
module.exports = withSass({
  sassLoaderOptions: {sourceMap: true}
})
```

**Comment by aurelienbobenrieth** [comment]
With that config I still just have the final main .scss file in my devtool. 

But thank you for trying to help !

**Comment by ruslansavenok** [comment]
@aurelienbobenrieth can you publish your code somewhere?
