### ISSUE TITLE
Warnings on peer deps

### ISSUE THREAD

**Issue by andrewmclagan** [zeit/next-plugins#193]
`warning "@zeit/next-sass > sass-loader@6.0.6" has unmet peer dependency "webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0".`

when installing

**Comment by skout90** [comment]
+1

**Comment by andrewmclagan** [comment]
hmm..

**Comment by timneutkens** [comment]
Either way, this will never be fixed, as Next.js handled installing/configuring webpack. It's a warning coming from NPM 🤷‍♂️
