### ISSUE TITLE
CSS Load issue while importing from external CSS file for @zeit/next-css version ^0.2.0

### ISSUE THREAD

**Issue by chinmaydalvi** [zeit/next-plugins#195]
following is my package.json with React, Next js and `@zeit/next-css` version
```
{
  "name": "ssr",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "author": "Chinmay Dalvi",
  "license": "ISC",
  "dependencies": {
    "@zeit/next-css": "^0.2.0",
    "next": "^6.0.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0"
  }
}
```

Following  is my `pages/index.js` file in which I am loading css from `/static/index.css` file. 
```
import '../static/index.css';
import Card from './Card';

export default () => (
    <div className="App">
        <header className="App-header">
            <img src="/static/logo.png"
                className="static-logo" alt="logo"/>
        </header>
        <div className="Grid">
            <Card />
            <Card />
            <Card />
        </div>
    </div>
);
```
I have also set the Configuration in `next.config.js` file 
```
const withCSS = require('@zeit/next-css')
module.exports = withCSS()
```

But the CSS in external file  `/static/index.css` is not loading in index.js . By watching One of the video from e-learning website i downgraded the `@zeit/next-css` version from `^0.2.0` to `0.0.7` in `package.json` and then ran `npm install`

And Suprisingly it loaded the CSS successfully from `index.css` in Development mode.
But it is still not loading CSS from production build.

**Comment by Fishbeard** [comment]
you should create _document.js in the pages/  and set correctly

**Comment by chinmaydalvi** [comment]
Thanks @Fishbeard  This issue if fixed
