### ISSUE TITLE
How to remove unused CSS and use webpack-plugin-critical ?

### ISSUE THREAD

**Issue by 2monkey** [zeit/next-plugins#202]
I work with ( withCss(withSass( ) and i tried to remove the unused css with purifycss but cant get it running.
And i only want to load the critical css first with webpack-plugin-critical but i cant access the build id folder of next.js

**Comment by JamesRosenthal** [comment]
I'm having an issue with this as well, I tried just adding the plugin to the postcss config's plugins but the version numbers are off, I'd have to downgrade postcss to get it working.

**Comment by febinsathar** [comment]
+1

**Comment by timneutkens** [comment]
As you've followed the issue template already by posting on spectrum I'm going to close this issue.
