### ISSUE TITLE
How to use multiple less files?

### ISSUE THREAD

**Issue by httpiago** [zeit/next-plugins#205]
I'm trying for a few hours to make a more organized folder scheme in "./pages" where each page has its own style file, something like this:

```
pages
├── About
│   ├─ index.js
│   └─ styles.less
└── Home
     ├─ index.js
     └─ styles.less
```
I'm importing this way, into every "index.js" of the folders: `import './styles.less'` but it just does not seem to work, apparently just to use a style file in the whole application :(

Can only import 1 file or am I doing something wrong?

my next.config.js:
```
const withLess = require('@zeit/next-less')
const withCSS = require('@zeit/next-css')

module.exports = withCSS(withLess())
```

**Comment by miukimiu** [comment]
Hi @httpiago,

Your structure should work! 

You need a `_document.js` file where you need to include your compiled `CSS` file:

```
import Document, { Head, Main, NextScript } from 'next/document'


export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps }
  }

  render() {
    return (
      <html>
        <Head>
          <link rel="stylesheet" href="/_next/static/style.css" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    )
  }
}
```

Then in your `next.config.js`:

```
const withLess = require('@zeit/next-less')
module.exports = withLess()
```

I tested with this and your structure worked well:
```
pages
├── About
│   ├─ index.js
│   └─ styles.less
└── Home
     ├─ index.js
     └─ styles.less
```

The working solution:
[testing-next.zip](https://github.com/zeit/next-plugins/files/2154632/testing-next.zip)

**Comment by BosenY** [comment]
But i want to use style.less in every compoent and every page, and then it just does not seem to work...

**Comment by miukimiu** [comment]
In the zip folder that I sent, I'm importing a less file into the `index.js` of the About folder. And I'm importing **another** less file into the `index.js` of the Home folder and it's working:

https://testing-next-dkzbtqsxke.now.sh/About
https://testing-next-dkzbtqsxke.now.sh/Home

**Comment by httpiago** [comment]
I'm using the same and example and it still does not work until today, it only imports the first .less file but those of the other components it ignores.
Can only contain one style file per page?

**Comment by timneutkens** [comment]
Try `next@canary` with `@zeit/next-less@canary`. Should be fixed there.

**Comment by kenjinp** [comment]
Does not work with imported components as of today
