### ISSUE TITLE
react-dates

### ISSUE THREAD

**Issue by markolofsen** [zeit/next-plugins#206]
I'm trying to use [react-dates](https://github.com/airbnb/react-dates) but native css-styles of the plugin not applied...

**next.config.js**
```
const withCSS = require('@zeit/next-css')
const withSass = require('@zeit/next-sass')
const autoprefixer = require('autoprefixer');
module.exports = withCSS(withSass({
  plugins: [
    {
      autoprefixer: {},
    },
    {
      'postcss-css-variables': {},
    }
  ],
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  },
....
}))
```

**Comment by alfredrumss** [comment]
the same thing is happening to me.  I don't know what I must to do.

**Comment by alfredrumss** [comment]
@markolofsen  I am was working with @[zeit/next-sass plugin](https://github.com/zeit/next-plugins/tree/master/packages/next-sass).  And I wonder how can I import some .css external, for example with react-dates. I don't know yet. But I just copied "the react-dates/lib/css/_datepicker.css" in another file into my project, with the extension ".scss" and worked...

It just a workaround. 

It's something about some Loader css but I don't know build it.

**Comment by markolofsen** [comment]
Strange, I did it too, but styles didn't applied

**Comment by markolofsen** [comment]
**Resolved! Necessary specifying _datepicker.css in <header> in _document.js**
