### ISSUE TITLE
Styled Component issue when upgrading 0.1.1 > 1.1.0

### ISSUE THREAD

**Issue by lucasnorman** [zeit/next-plugins#210]
Getting an error after I upgraded from 0.1.1 to 1.1.0. I made a custom StyledFunction type so that I can use props with them.  here is my with props function: 

    type StyledFunction<T> = styledComponents.ThemedStyledFunction<
        T,
        IThemeInterface
    >;

    function withProps<T, U extends HTMLElement = HTMLElement>(
        styledFunction: StyledFunction<React.HTMLProps<U>>,
    ): StyledFunction<T & React.HTMLProps<U>> {
        return styledFunction;
    } 

And the error I am getting:

    Syntax Error: Unexpected token, expected ";" (3:5)

    1 | import * as styledComponents from "styled-components";
    2 |
    > 3 | type StyledFunction<T> = styledComponents.ThemedStyledFunction<
      |        ^
    4 |     T,
    5 |     IThemeInterface
    6 | >;

**Comment by timneutkens** [comment]
Styled components is not a next plugin.
