### ISSUE TITLE
How to add includePaths to sass-loader

### ISSUE THREAD

**Issue by chacbumbum** [zeit/next-plugins#22]
How to add `includePaths` to sass-loader?

**Comment by chacbumbum** [comment]
I had clone [next-sass](https://github.com/zeit/next-plugins/tree/master/packages/next-sass) to local and edit it a little.

```javascript
const { cssModules, sassOptions = {} } = nextConfig;
///
options.defaultLoaders.sass = cssLoaderConfig(config, extractCSSPlugin, {
    cssModules,
    dev,
    isServer,
    loaders: [
        {
            loader: 'sass-loader',
            options: sassOptions
        }
    ]
});
```
Hope it will be in the internal package

**Comment by timneutkens** [comment]
@chacbumbum feel free to send a pull request allowing the configuration 👍

I'd call the property: `sassLoaderOptions` 👍

**Comment by chacbumbum** [comment]
Maybe I should close this issue

**Comment by timneutkens** [comment]
I'd like this option.

**Comment by timneutkens** [comment]
Ah you made the PR #37
