### ISSUE TITLE
When using next-css and next-sass meanwhile, only one can work

### ISSUE THREAD

**Issue by wslx520** [zeit/next-plugins#223]
Hi, I tried to use next-css and next-sass meanwhile, but only one can work.

```
module.exports = withCSS(withSASS(withOptimizedImages(config)));
```

who could work depends on who is outside of parenthesis (；´д｀)ゞ

Could someone help?

**Comment by Janpot** [comment]
https://github.com/zeit/next-plugins/issues/127#issuecomment-377905928

**Comment by timneutkens** [comment]
Fixed in https://github.com/zeit/next-plugins/pull/228
