### ISSUE TITLE
Using withSass and withLess plugins in the same project conflicts with only one style.css

### ISSUE THREAD

**Issue by PSPanesar** [zeit/next-plugins#240]
I have a next JS project and i have added the withSass and withLess plugins to my project. One external library requires Less so i am stuck with using that and my project uses Sass otherwise.

The problem i have is that when i build the project only one style.css is output in the .next/static/ directory and so only either Sass or Less can be used but they can't be used together. One always outputs to the style.css but then blocks the other.

Could anyone help with how i can use these two together? 

I have looked through all the Docs re options but can't get this to work.

Thanks

**Comment by timneutkens** [comment]
Fixed on next@canary and next-css@canary
