### ISSUE TITLE
next-css Production Example

### ISSUE THREAD

**Issue by julmot** [zeit/next-plugins#25]
The example in [this documentation](https://github.com/zeit/next-plugins/tree/master/packages/next-css#production-usage) points out to statically `<link>` to the statically generated CSS file. However, when doing so this will also apply to dev environments, where this link may be 404 or has outdated CSS styles. Please demonstrate an example that only uses this static file reference for production.

**Comment by thekevinscott** [comment]
@ScottPolhemus [has a good solution here](https://github.com/zeit/next-plugins/issues/1#issuecomment-363263664) that I'm using with success:

```
<Head>
  {!this.props.dev && (
    <link rel="stylesheet" href={`${this.props.__NEXT_DATA__.assetPrefix}/static/style.css`} />
  )}
</Head>
```

I'm actually using `process.env.NODE_ENV` instead of `this.props.dev` but I believe either one works.

**Comment by julmot** [comment]
@thekevinscott Thanks for you reply. Where does this `props.dev` variable come from? Actually I don't know if using `process.env.NODE_ENV` is safer, as it won't be available in browser environments.

**Comment by thekevinscott** [comment]
Good point. We're rendering all our HTML on the server so it works fine for us but I can see how that'd be a concern. You could potentially set it as in the webpack config in `next.config.js`.

I'm not sure where `props.dev` is coming from, we may need one of the authors to weigh in here on best practice.

**Comment by ScottPolhemus** [comment]
The example above was specifically for use in a custom document component, which receives `dev` and `__NEXT_DATA__` props as shown. I believe if you wanted to use a similar approach elsewhere you would need to provide the values in a different way (maybe using something like webpack's [DefinePlugin](https://webpack.js.org/plugins/define-plugin/) to make variables from your webpack config available to your compiled JS). I could be wrong but I don't *think* Next provides these values in a globally-accessible way by default.

**Comment by julmot** [comment]
@ScottPolhemus Even when defining it using Webpack's DefinePlugin, should you relay on `process.env.NODE_ENV` or something different?

**Comment by ScottPolhemus** [comment]
You'd probably be better off using the `dev` option that is provided to the webpack config function in `next.config.js` for this. Here's an example of how that might look:
```
const webpack = require('webpack')

module.exports = {
  webpack: (config, { dev }) => {
    config.plugins.push(
      new webpack.DefinePlugin({
        NEXT_ENV: dev ? JSON.stringify('development') : JSON.stringify('production')
      })
    )
    
    return config
  }
}
```
With this configuration, you could then check for `NEXT_ENV === 'production'` in your component to determine if you need the `<link>` tag:
```
<Head>
  {NEXT_ENV === 'production' && (
    <link rel="stylesheet" href="/_next/static/style.css" />
  )}
</Head>
```

**Comment by julmot** [comment]
@ScottPolhemus Thanks for your reply. Even if this question was out of topic, do you have an idea how to differentiate between server and client when not inside `getInitialProps`?
