### ISSUE TITLE
next-sass: How use with component-level SCSS files (not a global styles file)?

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/next-plugins#260]
I use component-level SCSS files like this (because of migration from non-Next.js project), e.g:

    components/MyComponent.js
    components/MyComponent.scss

In components/MyComponent.js:

    import 'MyComponent.scss'

My `next.config.js` looks like:

    const withSass = require('@zeit/next-sass')
    module.exports = withSass({
      cssModules: true
    })

I get no compile errors but the resulting CSS is not included → the component isn’t styled. Any tips?

**Comment by timneutkens** [comment]
https://github.com/zeit/next-plugins/tree/master/packages/next-css#usage

It still compiles to a single file.

**Comment by tomsoderlund** [comment]
Thanks @timneutkens for clarifying – it was the `_document.js` file I was missing.

**Comment by timneutkens** [comment]
In Next 7 it'll be automatically injected
