### ISSUE TITLE
next-css & next-typescript

### ISSUE THREAD

**Issue by romainquellec** [zeit/next-plugins#269]
Hi.

I can't use next typescript with next css.
I tried : 

- with next compose plugins
- with next-canary
- with extract text webpack plugins
- some other webpack plugins

With no success. Does anyone have the same problem ?

```
const withPlugins = require('next-compose-plugins')
const withTypescript = require('@zeit/next-typescript')
const withCSS = require('@zeit/next-css')

module.exports = withPlugins([withTypescript,withCSS])
```

Error :

```
UnhandledPromiseRejectionWarning: Error: Chunk.entrypoints: Use Chunks.addGroup instead
```

**Comment by timneutkens** [comment]
Should be fine if you use latest next-css + Next 7
