### ISSUE TITLE
next-less not generating style.css

### ISSUE THREAD

**Issue by nemixe** [zeit/next-plugins#270]
**Behavior**
install 'npx create-next-app --example with-next-less with-next-less-app'
add .gitignore write '.next' inside it
install now cli
run 'now'
**Expected**
css from less is generated

**Comment by timneutkens** [comment]
Fixed in Next 7 + next-less 1.0

**Comment by nemixe** [comment]
now it's not generating css on both localhost and now cli, maybe there's a special way to work with this version

**Comment by nemixe** [comment]
@timneutkens can you open this again ?

**Comment by kachkaev** [comment]
@nemixe have you tried `@zeit/next-less@1.0.1` (released 3 hours ago)?

**Comment by nemixe** [comment]
fixed, i placed 

> import '../styles.css' 

to _app.js and it work perfectly
