### ISSUE TITLE
Next CSS not working

### ISSUE THREAD

**Issue by joaogarin** [zeit/next-plugins#278]
Hello,
I am trying to load some CSS using 
@zeit
/with-css for the next config. however I get some strange errors, the CSS import comes from a package in a library that is using like this  :
```require('@reach/menu-button/styles.css');```
The error I get is : 
These dependencies were not found:

```* aws-sdk in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/publish.js, ./node_modules/fsevents/node_modules/node-pre-gyp/lib/info.js and
 1 other
* child_process in ./node_modules/fsevents/node_modules/detect-libc/lib/detect-libc.js, ./node_modules/fsevents/node_modules/node-pre-gyp/lib/te
stbinary.js and 3 others
* fs in ./node_modules/chokidar/index.js, ./node_modules/chokidar/lib/nodefs-handler.js and 62 others
* module in ./node_modules/mini-css-extract-plugin/dist/loader.js, (webpack)/lib/NormalModule.js and 1 other```

To install them, you can run: npm install --save aws-sdk child_process fs module

similar to the one posted here : https://github.com/zeit/next.js/issues/4940
My config looks like : 

```// next.config.js
const withCSS = require('@zeit/next-css');
const prod = process.env.NODE_ENV === 'production';
module.exports = withCSS({
    serverRuntimeConfig: { // Will only be available on the server side
        ...
    },
    publicRuntimeConfig: { // Will be available on both server and client
        ...
    }
})
```

To me it really looks like the problem is unrelated to the require being inside a node_module, because even if I comment it out I get the same errors in running the app with "withCSS()".

I also opened a thread in spectrum for this problem https://spectrum.chat/thread/28dcfcee-2475-4199-8041-b2766da1ec29

**Comment by timneutkens** [comment]
Can you create a minimal reproduction in a GitHub repo.

**Comment by joaogarin** [comment]
Ok. sorry for the delayed response. I have basically figured out what makes it break, in some occasions I am loading the config in order to access publicRuntimeConfig like so : 

``` 
const config = require('./../next.config.js');
const { publicRuntimeConfig } = config;
const SITENAME = publicRuntimeConfig.SITENAME;
```

This is what breaks..now..I dont yet know why. Its definitely something reproduceable I guess so in case I cant find more I can try making a replication on the with-next-css example repo. will in the meanwhile see if there is a better way of doing this..

**Comment by joaogarin** [comment]
https://github.com/zeit/next.js/blob/canary/examples/with-universal-configuration-runtime/pages/index.js#L2 seems like a better way to load it;) and works! 🤦‍♂️  not sure where I got this idea from.. =/ in case anyone stumbles on this.. I will close the issue as apparently its a non-bug sorry for this..

**Comment by timneutkens** [comment]
Ah that makes a *lot* of sense, we might add a warning for import next.config.js in the future, there's no case where you'd want to do that in a page afaik.

**Comment by timneutkens** [comment]
Could you create a new issue for that, following the issue template, so that I can add the correct labels to it for someone that wants a challenge 👌

**Comment by joaogarin** [comment]
Will most definitely do! Thanks for all the hard work :) Cheers!

**Comment by joaogarin** [comment]
Just to be clear here sorry, the problem was that I was using a require statement and not an import statement for loading config. I was not loading config from a page, is that not a good idea generally? I dont think I ever did that but didn't have a clear idea that would be a problem, thats what you mean with the issue right?

In regards to why I was using a require statement..I have no idea but I am sure I have seen it somewhere..so maybe someone else can also run into some situations when using require instead of import.. the docs seem consistent in this though : 

https://github.com/zeit/next.js/#exposing-configuration-to-the-server--client-side
