### ISSUE TITLE
next-source-maps missing source maps for commons.js

### ISSUE THREAD

**Issue by JonAbrams** [zeit/next-plugins#288]
![image](https://user-images.githubusercontent.com/1243092/46031690-6ec44880-c0ae-11e8-9756-7aa1c784e7cf.png)

I've got source maps for individual pages, but not the commons bundle.

**Comment by azizhk** [comment]
Looking at the files structure I'm assuming you are using next v6.
I'm getting same error from next v7.

**Comment by azizhk** [comment]
Oh ok then, same issue. Sourcemaps not working,
From yarn.lock:

```
"@zeit/next-source-maps@^0.0.3":
  version "0.0.3"

"@zeit/next-typescript@1.1.1":
  version "1.1.1"

"@zeit/next-sass@^1.0.1":
  version "1.0.1"

"@zeit/next-css@1.0.1":
  version "1.0.1"

next@^7.0.0:
  version "7.0.0"

uglify-es@^3.3.4:
  version "3.3.9"

uglify-js@^3.1.4:
  version "3.4.9"

uglifyjs-webpack-plugin@^1.2.4:
  version "1.3.0"

webpack@4.19.0:
  version "4.19.0"

webpack-sources@^1.0.1, webpack-sources@^1.1.0, webpack-sources@^1.2.0:
  version "1.3.0"

webpack-sources@1.2.0:
  version "1.2.0"
```

I think this has something to do with uglify-js and uglify-es. I'm going to add `resolutions` to my package.json to see if I can find what version broke this.

**Comment by azizhk** [comment]
Hey @JonAbrams can you tell me if your client source-maps are coming up?
I have no client source maps, and the commons bundle source map that you mentioned.

**Comment by azizhk** [comment]
Ok I find no trace of UglifyJsPlugin in next.js but I think they have replaced it with TerserPlugin.
I added this and got sourcemaps
```
config.optimization.minimizer = [new TerserPlugin({
  parallel: true,
  sourceMap: true,
  cache: true
})]
```
Creating a PR, once I can confirm things are working.

**Comment by JonAbrams** [comment]
Nice find @azizhk!
