### ISSUE TITLE
@Next 7.0.0 @next-css 1.0.1 doesn't work correctly

### ISSUE THREAD

**Issue by ITforHome** [zeit/next-plugins#291]
Thanks a lot for Next.JS. It is a very nice and simple solution to create a SSR-based React-App. I need some css-styles in my App and so i follow the README-File for the next-css plugin:

1. `npm install --save @zeit/next-css`
2. i create a `next.config.js` in my root-directory and paste this: `const withCSS = require('@zeit/next-css')
module.exports = withCSS()`
3. i create a `style.css` file with some css-rules
4. import the style.css file in my component as follows:
`import "../style.css"
export default () => <div className="example">Hello World!</div>
`

but it doesn't work. I get the errors:

## from Browser:

`Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.`

## from Console:

`500 Internal Server Error`

How can i solve the issue to use css in my SSR-App. Thanks for your answer...
I also try the canary version from next and next-css plugin, but no change

**Comment by ITforHome** [comment]
i have found an alternative to use css-files:

```javascript
<Head>
    <link rel="stylesheet" href="../static/index.css" />
</Head>
```

but it would be nice, of course, if you could use the import statement for this...

**Comment by ITforHome** [comment]
I solved the problem. I haved trouble with the `next.config.js` file. I use multiple plugins and i haved multiple `module.exports`- statements. This Issue can be close now.

**Comment by gameboyVito** [comment]
@ITforHome how to use multiple plugins together? I can't import css file in Next@7.0.2, with @zeit/next-css@1.0.1

My next.config.js:
```
const withBundleAnalyzer = require('@zeit/next-bundle-analyzer')
const withCSS = require('@zeit/next-css')
const withPlugins = require('next-compose-plugins')
const withTM = require('@weco/next-plugin-transpile-modules')

module.exports = withPlugins([withTM, withCSS, withBundleAnalyzer], {
})
```

My use case:
```
import 'rc-progress/assets/index.css'
```

Error:
```
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
TypeError: Cannot read property 'local' of undefined
```
