### ISSUE TITLE
Can't pass variables to styled-jsx with typescript

### ISSUE THREAD

**Issue by monzou** [zeit/next-plugins#30]
Hello, thank you for awesome plugins !

I found a problem when using typescript and styled-jsx. If I set target of typescript to **es5**, I can not pass variables to styled-jsx.

```typescript
import * as React from 'react'
const backgroundColor = '#eee'

export default () => (
  <div className='hello'>
    <p>Hello World</p>
    <style jsx>{`
      .hello {
        background-color: ${backgroundColor}; // <--- ERROR !!
        padding: 100px;
        text-align: center;
        transition: 100ms ease-in background;
      }
    `}</style>
  </div>
)
```

If I set the `target` of `tsconfig.json` to **es2015**, this problem does not occur. However, if **es5** is specified as target, the following error occurs. 

```
Syntax Error: <style jsx>{`some css`}</style>), but got BinaryExpression

  1 | import * as React from 'react';
  2 | var backgroundColor = '#eee';
> 3 | export default (function () { return (<div className='hello'>
    |                                       ^
  4 |     <p>Hello World</p>
  5 |     <style jsx>{"\n      .hello {\n        background-color: " + backgroundColor + ";\n        padding: 100px;\n        text-align: center;\n        transition: 100ms ease-in background;\n      }\n    "}</style>
  6 |   </div>); });
```

In addition, if I do not pass variables to styled-jsx, even if target is es5 it works fine.

The following is a summary of the reproduction code.
https://gist.github.com/monzou/10fb15080cfc746e5a0dea1ee15134bf

Is there a solution to this problem ?
Thanks.

**Comment by timneutkens** [comment]
Why would you set the target to es5? Typescript is transpiled and then passed off to babel which transpiles it to es5 compatible code.
