### ISSUE TITLE
It is not behaving as expected

### ISSUE THREAD

**Issue by zscaiosi** [zeit/next-plugins#31]
I define an interface, then pass it to my Component as Props and/or State the interface doesn't really apply.
Because if I try to create a state variable diferrent from the interface it doesn't throw any error neither points the error out.

But if I implement a function (like someFunction()) with typed params and try to call it, VS Code will tell me it is wrong, but still tsc will not throw an error.

Check it out here:
```
import React from 'react';

interface ops {
  a: number;
}

class Index extends React.Component<ops, ops> {
  constructor(props: ops){
    
    super(props);

    //Should tell me there is no "b" in the state's type
    this.state = {
      b: 'olar'
    }
  }

  someFunction(param1: string, param2: number){
    return param1+param2.toString();
  }

  render(){
    return(
      <div>
        { this.someFunction(5, {attr: 'it is behaving as expected'}) }
      </div>
    );  
  }

}

export default Index;
```
My tsconfig.json file:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "jsx": "preserve",
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "typeRoots": [
      "./node_modules/@types"
    ],
    "lib": [
      "dom",
      "es2015",
      "es2016"
    ]
  }
}
```

What am I doing wrong?

**Comment by timneutkens** [comment]
next-typescript doesn't do type checking as defined here: https://github.com/zeit/next-plugins/blob/master/packages/next-typescript/index.js#L22. Feel free to make a PR to set that as an option.

**Comment by zscaiosi** [comment]
Ok, I will make a PR for that!
Thanks!
