### ISSUE TITLE
@zeit/next-mdx has different signature with other plugins

### ISSUE THREAD

**Issue by tkesgar** [zeit/next-plugins#320]
I noticed that next-mdx has a different signature with other plugins:

```js
// next-mdx/index.js
module.exports = (pluginOptions = {}) => (nextConfig = {}) => {

// next-sass/index.js
module.exports = (nextConfig = {}) => {

// next-bundle-analyzer/index.js
module.exports = (nextConfig = {}) => {
```

It is documented in the readme but I didn't notice the two `()` after `require('@zeit/next-mdx')`.

Plugin chaining also become uncool:

```js
module.exports = withBundleAnalyzer(withMdx()(withSass()))
```

I think we can move `pluginOptions` out and use an arbitrary property such as `mdxConfig`, just like how next-bundle-analyzer uses `bundleAnalyzerConfig`.

**Comment by timneutkens** [comment]
This is expected and we're moving the other plugins to this model.
