### ISSUE TITLE
Update @zeit/next-mdx peer dependencies

### ISSUE THREAD

**Issue by NathanielHill** [zeit/next-plugins#333]
`@mdx-js/mdx` `0.16.0` is out. Can we update?

**Comment by iamstarkov** [comment]
`@mdx-js/mdx@1.x` is out.

**Comment by timneutkens** [comment]
The MDX plugin was moved here: https://github.com/zeit/next.js/tree/canary/packages/next-mdx

It no longer has a direct dependency on a MDX version.

**Comment by iamstarkov** [comment]
@timneutkens does it work with `mdx@1.x`?

**Comment by timneutkens** [comment]
Sure why not.

**Comment by iamstarkov** [comment]
@timneutkens I dunno, backwards incompatible changes due to major release perhaps
