### ISSUE TITLE
Next-workers: window is not defined

### ISSUE THREAD

**Issue by revskill10** [zeit/next-plugins#337]
I got error `window is not defined` with `next-worker` plugins.
Do you know how to resolve this ?

**Comment by revskill10** [comment]
@timneutkens I got error
```
npm ERR! code E404
npm ERR! 404 Not Found: @zeit/next-worker@canary
```
when trying installing with `npm i --save @zeit/next-worker@canary`

**Comment by timneutkens** [comment]
It's actually `workers`, so `@zeit/next-workers@canary`

**Comment by revskill10** [comment]
Thanks @timneutkens .

**Comment by aequasi** [comment]
Thanks @timneutkens 

Also @revskill10, depending on your NPM version, you dont need to speciy `--save` anymore :)
