### ISSUE TITLE
How to make it works with multi plugins?

### ISSUE THREAD

**Issue by rohmanhm** [zeit/next-plugins#34]
I think this issue might similar to #20 

If I want to use a plugin, then I need to export on `next.config.js` like this
```js
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  cssModules: true,
  webpack: (config) => {
    return config
  }
})
```

But, how to use it with 2 or more plugins?

As I read on #20, I can't use it like 
```js
module.exports = withCSS(withTypescript(withSass(...)))
```

Thanks

**Comment by timneutkens** [comment]
You can do exactly this:

```
withCSS(withTypescript(withSass({
 cssModules: true,
 webpack: (config) => {
    return config
 }
})))
```

**Comment by vinutha93bnvs** [comment]
Use this https://github.com/JerryCauser/next-compose to export multiple modules from next.config.js

**Comment by dryleaf** [comment]
Along with the `css` configurations mentioned here, What if I want to export also the following settings in `next.config.js`:
```
module.exports = {
  useFileSystemPublicRoutes: false,
  poweredByHeader: false
}
```
How can this be achieved?

**Comment by jcruzdzk** [comment]
What is the best practice for this @timneutkens  :

´const withCSS = require('@zeit/next-css');

module.exports = {
  poweredByHeader: false,
};

module.exports = withCSS({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: "[local]___[hash:base64:5]",
  },
});
´

**Comment by dryleaf** [comment]
Did anyone find a solution multiple plugin configurations like described in https://github.com/zeit/next-plugins/issues/34#issuecomment-527658864 ?

**Comment by vhnam** [comment]
@dryleaf  @jcruzdzk  I tried this and success.

```js
const withCSS = require('@zeit/next-css');

module.exports = withCSS({
  poweredByHeader: false,
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[local]___[hash:base64:5]',
  },
  webpack(config) {
    config.module.rules.push({
      test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
        },
      },
    });
    return config;
  },
});

```
