### ISSUE TITLE
Custom server with typescript

### ISSUE THREAD

**Issue by echoulen** [zeit/next-plugins#35]
I compile `.ts` to `.js` by `tsc` with express server
`@zeit/next-typescript` resolve the next command with typescript but server.ts from outside

For example
```
import * as next from "next";

const port = parseInt(process.env.PORT, 10) || 3000;
const app = next({dev: true});
app.prepare().then(() => {
    server.listen(port, (err) => {
        if (err) {
            throw err;
        }

        console.log(`> Ready on http://localhost:${port}`);
};
```

Is possible to use `@zeit/next-typescript` with custom server?

**Comment by timneutkens** [comment]
Compiling the server is unrelated to Next. Next is not aware of the custom server, and the custom server initiates webpack etc, so we can't compile the server than runs webpack using webpack obviously 😄
