### ISSUE TITLE
TypeError: Cannot read property 'splitChunks' of undefined

### ISSUE THREAD

**Issue by victorkernes** [zeit/next-plugins#358]
Followed the directions of adding the snippet below after using `npm install --save @zeit/next-css`:

```
const withCSS = require('@zeit/next-css')
module.exports = withCSS({
  cssModules: true
})
```
Received the following error after running locally:

`TypeError: Cannot read property 'splitChunks' of undefined`

Anyone else running into this?

**Comment by timneutkens** [comment]
Sounds like you're not on Next.js 7.0.0 or later.

**Comment by victorkernes** [comment]
Hi @timneutkens, I updated to 7.0.2 and still getting the same error.
