### ISSUE TITLE
How to resolve png compilation issue?

### ISSUE THREAD

**Issue by samartha230194** [zeit/next-plugins#36]
I am trying to import leaflet.css from leaflet package. I got a  error stating  
"error  in ./node_modules/leaflet/dist/images/marker-icon.png

Module parse failed: Unexpected character '�' (1:0)".

I have attached the image below.
![error](https://user-images.githubusercontent.com/13852394/36091739-d09c1150-100a-11e8-9eeb-badb3128e6d5.png)

**Comment by timneutkens** [comment]
Sounds like you need to add a loader for png files.

**Comment by samartha230194** [comment]
Hi,
Yes installing the loader solved the issue.

Thank you.
