### ISSUE TITLE
Problem with TypeScript Compilation

### ISSUE THREAD

**Issue by pkellner** [zeit/next-plugins#361]
WebStorm automatically generates TypeScript automatically for code that looks like:

`Speakers.getInitialProps = async ({req}) => {
    const isServer = !!req;`

and creates an interface that looks like this:

`    getInitialProps: ({req}: { req: any; }) => 
        Promise<{ isLoading: boolean; hasErrored: boolean; speakers: any; isServer: boolean; } |
            { speakers: never[]; hasErrored: boolean; isServer: boolean; errorMessage: any; }>;`

The JavaScript fails to compile. I reported this the WebStorm and they say:

> Declare property quick fix is provided by TypeScript compiler service, not by Webstorm itself, and the code generated by it is perfectly valid, syntactically correct typescript.
> Looks like the next.js plugin responsible for transpiling .tsx (@zeit/next-typescript/babel? ) can't handle constructions like {req, query}: { req: any; query: any; }. I'd suggest reporting this issue to https://github.com/zeit/next-plugins/issues/

**Comment by timneutkens** [comment]
I'm not sure what you're asking 🤔

**Comment by pkellner** [comment]
According to JetBrains (WebStorm), they are saying that the transpilation done with the nextjs plugin is incorrect and should be corrected. JetBrains is claiming that the typescript they are creating for the signature first listed is correct and that there is a bug that needs to be fixed in the next.js plugin.

**Comment by pkellner** [comment]
This is confirmed as fixed in 9.0.5. That is, debugging on the fly works with typescript as the express server. I did have to run node with the `--require ts-node/register` option. I also had to make sure my .js files were removed. That is, I had previously server.ts and server.js.  removing server.js was necessary for debugging to work.
