### ISSUE TITLE
Custom document breaks style plugins

### ISSUE THREAD

**Issue by dextermb** [zeit/next-plugins#368]
Hey there,

I'm coming back to use Next JS after taking a break for a while. I've noticed that when I implement a custom document the style/link tags that should be injected do not get injected when I have a simple custom document.

Here's the custom document (`_document.jsx`):
```jsx
import Document, { Main, NextScript } from 'next/document';

class CustomDocument extends Document {
    static async getInitialProps(ctx) {
        // <snip>
    }

    render() {
        return (
            <html>
                <body>
                    <Main />
                    <NextScript />
                </body>
            </html>
        )
    }
}

export default CustomDocument;
```

Here's my custom app:
```jsx
import React from 'react';
import App, { Container } from 'next/app';

import '../styles/_app.scss';

class CustomApp extends App {
    static async getInitialProps({ Component, ctx }) {
        // <snip>
    }

    render () {
        const { Component, pageProps } = this.props

        return (
            <Container>
                <Component {...pageProps} />
            </Container>
        )
    }
}

export default CustomApp;
```

As you can see, both are fairly standard. I put the `scss` import into `_app.jsx` so that the styles will be globally injected rather than on specific pages. Here's my `next.config.js`:

```js
const scss = require('@zeit/next-sass');

module.exports = scss();
```

My top level stylesheet is in the valid path shown in `_app.jsx`, but it seems when I implement a custom `_document.jsx` (shown above) the `head` tag never seems to get populated correctly from webpack.

Rather than having the usual injected code it simply has:
```html
<html>
    <head>
        <script charset="utf-8" src="/_next/static/chunks/0.js"></script>
    </head>
    <body>
        <!-- Normal Next scripts and content -->
    </body>
</html>
```

I know I do not _need_ a custom document, but I wondered on what might be causing it to override `head` and not allow any injections?

**Comment by dextermb** [comment]
> @dextermb try to add `<Head>` into `<html>`
> `import Document, { Head, Main, NextScript } from 'next/document';`

An empty `<Head/>`?

**Comment by radeno** [comment]
When you don't have any custom meta like 
```
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0 viewport-fit=cover"
          />
          <link
            rel="icon"
            type="image/png"
            href="path/to/favicon"
            sizes="32x32 57x57 76x76 96x96 128x128 228x228"
          />
```

then empty

**Comment by dextermb** [comment]
> When you don't have any custom meta like
> 
> ```
> <Head>
>           <meta
>             name="viewport"
>             content="width=device-width, initial-scale=1.0 viewport-fit=cover"
>           />
>           <link
>             rel="icon"
>             type="image/png"
>             href="path/to/favicon"
>             sizes="32x32 57x57 76x76 96x96 128x128 228x228"
>           />
> </Head>
> ```
> then empty

My example shows that the HTML `head` is not being populated by webpack/babel, if a custom `_document` is set without a `head`. I am not interested in populating one for no reason.

I'll take a look at an empty `<Head />` tag.

**Comment by radeno** [comment]
You need to read documentation before 
https://github.com/zeit/next.js#custom-document

After example is sentence:
`All of <Head />, <Main /> and <NextScript /> are required for page to be properly rendered.`

**Comment by dextermb** [comment]
> You need to read documentation before
> https://github.com/zeit/next.js#custom-document
> 
> After example is sentence:
> `All of <Head />, <Main /> and <NextScript /> are required for page to be properly rendered.`

Ah! That's what I was looking for. I'll give it a go.

**Comment by radeno** [comment]
You are welcome.
