### ISSUE TITLE
iam noob, i use like doc but wont work, help

### ISSUE THREAD

**Issue by selique** [zeit/next-plugins#395]
when i try use sass plugin: 

`./styles/style.scss
Module build failed (from ./node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)`

**Comment by Timer** [comment]
Hey @selique, could you please post the contents of `./styles/style.scss`? This will help us figure out what's going on.

**Comment by selique** [comment]
@Timer 
![image](https://user-images.githubusercontent.com/1678894/52588276-376af400-2e23-11e9-9f14-0c39723df3ca.png)

**Comment by selique** [comment]
@Timer 
`{
  "name": "smartbank",
  "version": "1.0.0",
  "description": "portal smartbank institucional e internet banking",
  "main": "index.js",
  "author": "Moisés Lopes Ferreira | https://www.linkedin.com/in/selique/",
  "license": "ISC",
  "dependencies": {
    "@zeit/next-sass": "^1.0.1",
    "eslint": "^5.13.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.0.1",
    "eslint-plugin-jsx-a11y": "^6.2.1",
    "eslint-plugin-react": "^7.12.4",
    "next": "^8.0.0",
    "node-sass": "^4.11.0",
    "react": "^16.8.1",
    "react-dom": "^16.8.1"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "browserslist": [
    ">= 0.5%",
    "chrome >= 42",
    "and_chr >= 42",
    "and_ff >= 38",
    "android >= 4.4",
    "edge >= 12",
    "firefox >= 38",
    "ie >= 11",
    "ios_saf >= 9",
    "safari >= 9",
    "node 10"
  ],
  "devDependencies": {
    "autoprefixer": "^9.4.7"
  }
}`

**Comment by selique** [comment]
my package.json

![image](https://user-images.githubusercontent.com/1678894/52588479-b6602c80-2e23-11e9-8ad5-9e29d8aa18dc.png)

**Comment by selique** [comment]
i need solid exemple for use

**Comment by Timer** [comment]
Could you please provide your Git repo for us to clone? It'd help diagnosing the issue way quicker.

**Comment by selique** [comment]
> Could you please provide your Git repo for us to clone? It'd help diagnosing the issue way quicker.

https://github.com/selique/next-site-exemple

**Comment by pseudoramble** [comment]
I'm experiencing a similar issue as well. Unfortunately I don't have a repo to share right this moment, but some more specific details in my scenario:

`package.json`

```
"@zeit/next-css": "^1.0.1",
"next": "^8.0.0"
```

`next.config.js`

```
const withCSS = require('@zeit/next-css');
module.exports = withCSS();
```

I'm importing a CSS from an internal component lib stylesheet. It includes quite a bit of code.

Part of the error I'm seeing:

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

Is there any extra logging that can be flipped on to debug? I'm glad to try and dig up some more info. I'll also share if I figure out how to make it work.

**Comment by pseudoramble** [comment]
Sorry - I got ahead of myself adding the above comment. I found a fix here: https://github.com/zeit/next-plugins/issues/273. Basically it needs a workaround for font-loading and some images as well. It looks like it eventually might go into `next-css`. I'm not sure if this helps with `next-sass` though. Might be worth a check!

**Comment by selique** [comment]
i discovery the problem, its a loader fonts 

the solution:
i add this short part 

`    {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[name].[ext]",
              outputPath: "fonts/"
            }
          }
        ]
      }`

i modify my next.config.js to 

`const path = require("path");
const withSass = require("@zeit/next-sass");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");

const nextConfig = withSass({
  webpack(config, options) {
    config.module.rules.push(
      {
        test: /\.(raw)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        use: "raw-loader"
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[name].[ext]",
              outputPath: "fonts/"
            }
          }
        ]
      }
    );
    config.module.rules.push({
      type: "javascript/auto",
      test: /\.modernizrrc(\.json)?$/,
      use: ["expose-loader?Modernizr", "modernizr-loader", "json-loader"]
    });
    config.resolve = {
      alias: {
        modernizr$: path.resolve(__dirname, ".modernizrrc.json")
      }
    };
    if (config.mode === "production") {
      if (Array.isArray(config.optimization.minimizer)) {
        config.optimization.minimizer.push(new OptimizeCSSAssetsPlugin({}));
      }
    }
    return config;
  }
});

nextConfig.exportPathMap = () => {
  return {
    "/": { page: "/" }
  };
};

module.exports = nextConfig;
`

**Comment by selique** [comment]
the solution:
i add this short part

` { test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/, use: [ { loader: "file-loader", options: { name: "[name].[ext]", outputPath: "fonts/" } } ] }`

**Comment by selique** [comment]
do not  worked fix this with modifications, but now i know origin of trouble, if u can help-me @Timer brimo

**Comment by selique** [comment]
i found the solution for fix this


 

```javascript
> config.module.rules.push({
>       test: /\.(png|svg|eot|otf|ttf|woff|woff2)$/,
>       use: {
>         loader: "url-loader",
>         options: {
>           limit: 100000,
>           publicPath: "./",
>           outputPath: "static/",
>           name: "[name].[ext]"
>         }
>       }
>     });
```

**Comment by selique** [comment]
my final code:
next.config.js
```javascript
const path = require("path");
const withSass = require("@zeit/next-sass");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
const withFonts = require("next-fonts");

module.exports = withFonts({
  assetPrefix: "https://example.com",
  webpack(config, options) {
    return config;
  }
});
const nextConfig = withSass({
  webpack(config, options) {
    config.module.rules.push({
      test: /\.(raw)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      use: "raw-loader"
    });
    config.module.rules.push({
      type: "javascript/auto",
      test: /\.modernizrrc(\.json)?$/,
      use: ["expose-loader?Modernizr", "modernizr-loader", "json-loader"]
    });
    config.module.rules.push({
      test: /\.(png|svg|eot|otf|ttf|woff|woff2)$/,
      use: {
        loader: "url-loader",
        options: {
          limit: 100000,
          publicPath: "./",
          outputPath: "static/",
          name: "[name].[ext]"
        }
      }
    });
    config.resolve = {
      alias: {
        modernizr$: path.resolve(__dirname, ".modernizrrc.json")
      }
    };
    if (config.mode === "production") {
      if (Array.isArray(config.optimization.minimizer)) {
        config.optimization.minimizer.push(new OptimizeCSSAssetsPlugin({}));
      }
    }
    return config;
  }
});

nextConfig.exportPathMap = () => {
  return {
    "/": { page: "/" }
  };
};

module.exports = nextConfig;

```

**Comment by selique** [comment]
my final code:
next.config.js
```javascript
const path = require("path");
const withSass = require("@zeit/next-sass");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
const withFonts = require("next-fonts");

module.exports = withFonts({
  assetPrefix: "https://example.com",
  webpack(config, options) {
    return config;
  }
});
const nextConfig = withSass({
  webpack(config, options) {
    config.module.rules.push({
      test: /\.(raw)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      use: "raw-loader"
    });
    config.module.rules.push({
      type: "javascript/auto",
      test: /\.modernizrrc(\.json)?$/,
      use: ["expose-loader?Modernizr", "modernizr-loader", "json-loader"]
    });
    config.module.rules.push({
      test: /\.(png|svg|eot|otf|ttf|woff|woff2)$/,
      use: {
        loader: "url-loader",
        options: {
          limit: 100000,
          publicPath: "./",
          outputPath: "static/",
          name: "[name].[ext]"
        }
      }
    });
    config.resolve = {
      alias: {
        modernizr$: path.resolve(__dirname, ".modernizrrc.json")
      }
    };
    if (config.mode === "production") {
      if (Array.isArray(config.optimization.minimizer)) {
        config.optimization.minimizer.push(new OptimizeCSSAssetsPlugin({}));
      }
    }
    return config;
  }
});

nextConfig.exportPathMap = () => {
  return {
    "/": { page: "/" }
  };
};

module.exports = nextConfig;

```
