### ISSUE TITLE
next-less is not word when build

### ISSUE THREAD

**Issue by supeng911** [zeit/next-plugins#4]
Great work on Next.js 5.0!

I think that's a bug for next-less

I have make a test project, when I use "npm run dev", It worked well, but when I build it, is not worked,

the .next/static catalog has style.css

but the page can't find the css it‘s render like this "  href="/_next/a270d480-e3ee-4ed7-a055-5434f0caa191/page/_error.js" "

I have make a test project : https://github.com/supeng911/next-less-test

**Comment by timneutkens** [comment]
Added production usage documentation 🙏 https://github.com/zeit/next-plugins/tree/master/packages/next-less#production-usage

**Comment by alexindigo** [comment]
Thanks for the production docs @timneutkens 
Looks like it's missing CDN part though.
