### ISSUE TITLE
Which version to use for next-css and next-sass

### ISSUE THREAD

**Issue by kyle-mccarthy** [zeit/next-plugins#425]
It looks like there was a recent release with [this commit](https://github.com/zeit/next-plugins/commit/fb8f61e2a38b973626a3d607f425a2a7eeb82487), but next-css and next-sass both have 1.0.1 versions.  Should we be using the 0.2.1 release or the 1.0.1 release? 

https://www.npmjs.com/package/@zeit/next-css?activeTab=versions
https://www.npmjs.com/package/@zeit/next-sass?activeTab=versions

Mainly, I am trying to debug something related to #373 but am not sure if the intention is to remove mini-extract-css-plugin. Thanks!

**Comment by radeno** [comment]
@kyle-mccarthy if you want latest development version then use 0.2.1-canary. If you want stable, then use 1.0.1, and at last 1.0.2-canary is something between.

I know, confusing.
