### ISSUE TITLE
Analyze-bundles example does not run in dev mode 

### ISSUE THREAD

**Issue by lavir** [zeit/next-plugins#434]
# Bug report

# Describe the bug
`npm run dev` fails with an error in Analyze-bundles example
```
Failed to compile.

./node_modules/next/dist/client/next-dev.js 34:6
Module parse failed: Unexpected token (34:6)
You may need an appropriate loader to handle this file type.
| 
| 
> import('./noop');
| var _window = window,
|     assetPrefix = _window.__NEXT_DATA__.assetPrefix;
```

# Expected behavior
`npm run dev` should run in dev mode 

# System Information
*    @zeit/next-bundle-analyzer: "^0.1.2"
*   next: "8.0.3" and "v8.0.4-canary.23" (tested with both versions)
*    react: "^16.7.0"
*    react-dom: "^16.7.0"

**Comment by KB1RMA** [comment]
This might be more related to https://github.com/zeit/next.js/issues/6240 ?

**Comment by timneutkens** [comment]
Yep you're right @KB1RMA, tracking it there!
