### ISSUE TITLE
Commons css bundle not cached (served with cache-control: public, max-age=0)

### ISSUE THREAD

**Issue by wouterds** [zeit/next-plugins#439]
# Bug report

## Describe the bug

Commons css chunk served with `cache-control: public, max-age=0` header.

## Expected behavior

Expect the bundle to be served immutable, preferably with the same caching header as the js bundle (`cache-control: public, max-age=31536000, immutable`).

## Screenshots

![commons-chunk-css](https://user-images.githubusercontent.com/1210628/55317137-355f0200-5470-11e9-9e76-46dbcdc192ac.jpg)

![commons-chunk-js](https://user-images.githubusercontent.com/1210628/55317125-2ed08a80-5470-11e9-952b-91156e676f8b.jpg)

## System information

 - OS: macOS 10.14.3
 - Browser: Google Chrome 73.0.3683.86 64-bit
 - Version of Next.js: 8.0.3

## Additional context

My [next.config.js](https://gist.github.com/wouterds/b9a0daf1ec54dc242ea53e5d25b16bae), not doing anything crazy here. Feel free to [check it out live here](https://delta.app/en/markets).

**Comment by wouterds** [comment]
Workaround I'm currently using since our nextjs server is running in a container and is behind a reverse proxy anyway, I'm just forcing the Cache-Control header on all static assets.

```nginx
location ~ \.(?:ico|css|js|gif|jpe?g|png|webp|gif|svg)$ {
  proxy_pass http://next:3000;
  proxy_hide_header Cache-Control;
  add_header Cache-Control "public, max-age=31536000, immutable";
}
```

**Comment by charles4221** [comment]
I believe this issue was resolved in PR #335 within the code here on github, however when you install `@zeit/next-css` via npm or yarn I'm getting a version which still outputs the css to `static/css` instead of the newly updated `static/chunks` as per the PR. @timneutkens is there any timeline on when this fix will be pushed to npm?

**Comment by chase** [comment]
> I believe this issue was resolved in PR #335 within the code here on github, however when you install `@zeit/next-css` via npm or yarn I'm getting a version which still outputs the css to `static/css` instead of the newly updated `static/chunks` as per the PR. @timneutkens is there any timeline on when this fix will be pushed to npm? I'm still having this issue and have a massive build that's getting close to production release, so would really love to be able to resolve this :)

For some reason all these wonderful fixes have been hiding in the canary channel.
This should install next-css with the necessary fixes: `npm install --save @zeit/next-css@0.2.1-canary.4`

**Comment by haf** [comment]
This bug seems to be back with the built-in CSS support in nextjs with nextjs 9.2

**Comment by timneutkens** [comment]
@haf just checked and looks fine:

<img width="528" alt="Screen Shot 2020-02-25 at 13 52 02" src="https://user-images.githubusercontent.com/6324199/75249178-03683400-57d6-11ea-9a5f-337991fe3df7.png">

Note that if you use @zeit/next-sass / @zeit/next-css built-in support is disabled.

**Comment by haf** [comment]
@tim-phillips 
![image](https://user-images.githubusercontent.com/193115/75250328-678bf780-57d8-11ea-9994-a1a1979bab75.png)


```
next@^9.2.0:
  version "9.2.0"
  resolved "https://registry.yarnpkg.com/next/-/next-9.2.0.tgz#1adc85ad45143114cd22e6a68337f56319cd59d2"
  integrity sha512-c4gyJotZHuvq9dslum+Z2Z21jjb9qWMYybV+IS9yEg7hTjs8OyKU59snyJ1Bi0ul84OdyLOZ4ytjch9zMw9lEQ==
  dependencies:
```

**Comment by timneutkens** [comment]
You're not on the latest version of Next.js, please upgrade.

**Comment by haf** [comment]
Indeed, the last two patch versions seems to have fixed it! Thanks :)
