### ISSUE TITLE
[next-css] `:export` blocks in JS don't work from SSR

### ISSUE THREAD

**Issue by Ovyerus** [zeit/next-plugins#445]
I'm using `next-sass` for managing stylesheets, but that relies on [css-loader-config.js](https://github.com/zeit/next-plugins/blob/master/packages/next-css/css-loader-config.js) so this still applies.

When using `:export` blocks as defined by [ICSS](https://github.com/css-modules/icss#export) for CSS modules, the exported variables don't work when server-side rendered - this applied for both development and production builds (this gets fixed after HMR gets applied as shown following).

It appears that this is because css-loader-config.js doesn't bother transpiling when on the server side with `cssModules: false`, as shown below here:

https://github.com/zeit/next-plugins/blob/81cbfcb72fb810ac58a745961d226a7e7801043a/packages/next-css/css-loader-config.js#L100-L103

I'm not sure of the rationale behind doing this, but this ends up screwing with importing variables defined in `:export` blocks, as they don't end up getting transpiled to be able to do so, causing styles defined in JS - such as through emotion or styled-components - to not work unless HMR is run (which isn't possible in a production build). ([Sample gist of using these with emotion](https://gist.github.com/Ovyerus/aa98719afff6c33fcd8fb889ef057c34))

Looking further on, one might think they can just define `cssModules: true` to get stuff to be transpiled on the server:

https://github.com/zeit/next-plugins/blob/81cbfcb72fb810ac58a745961d226a7e7801043a/packages/next-css/css-loader-config.js#L105-L108

However this fully enables the CSS modules spec (I believe so at least), which then causes pre-existing styles to break, and the person might not want to use CSS modules, so that's a no go.

## Potential fix
Commenting out the former block which inserts `ignore-loader` appears to fix this issue without enabling CSS modules, so a possible fix for this would be to add another option, called `transpileCssOnServer` or something similar, which is then added to the check in that first block, like so:

```js
if (isServer && !cssLoader.options.modules && !transpileCssOnServer) {
    return ['ignore-loader']
}
```

Meaning that when the user manually sets the config option, this block skips, which causes it to transpile the CSS normally, fixing/avoiding this issue. Commenting out the block I haven't noticed any adverse issues, so I'm pretty certain this is a reasonable fix.

Alternatively, we could just remove this block altogether as I'm not sure what other people it has.

**Comment by stschindler** [comment]
There's a dirty workaround for this:

```
module.exports = withSass({cssModules: "x"})
```
