### ISSUE TITLE
@zeit/next-bundle-analyzer causes npm audit error

### ISSUE THREAD

**Issue by fabb** [zeit/next-plugins#451]
`next-bundle-analyzer` depends on `webpack-bundle-analyzer@3.0.2`, but there is an XSS problem in that dependency that is only fixed in `>=3.3.2`.

https://www.npmjs.com/advisories/826

**Comment by etaggus** [comment]
Any news on this? Been a while since this issue was opened..

**Comment by lydell** [comment]
@zeit/next-bundle-analyzer seems to have been deprecated in favor of @next/bundle-analyzer. 8.1.1-canary.44 of that package has an updated webpack-bundle-analyzer.

https://github.com/zeit/next.js/blob/9fa1101c7c7d6c81166c6565271296f1ebc3bf7d/packages/next-bundle-analyzer/package.json

```
npm install --save-dev @next/bundle-analyzer@canary
```

Note that the new package works slightly differently. It creates HTML files that you need to open yourself in the browser.
