### ISSUE TITLE
Can `next-source-maps` include source maps from within node_modules?

### ISSUE THREAD

**Issue by avivash** [zeit/next-plugins#469]
Hi, I'm using `next-source-maps`(which has worked great) to add source maps to our project.

I'm wondering though, if it's possible for it to include source maps from the `node_modules` folder? Or will those have to be added through webpack's [source-map-loader](https://github.com/webpack-contrib/source-map-loader)?

**Comment by timneutkens** [comment]
It creates sourcemaps for the output bundles. So if you want to do something like that you will indeed need to include the loader.

**Comment by avivash** [comment]
Sounds good, thanks 👍
