### ISSUE TITLE
next-sass: sass-loader version update needed

### ISSUE THREAD

**Issue by HyunSeob** [zeit/next-plugins#485]
For now, next-sass has only supported node-sass. But sass-loader has started to support dart-sass also. So it would be more useful to be able to choose Sass implementations. I think it will be needed to be updated sass-loader version to 7.1.0, and also be removed node-sass from peer dependencies.

**Comment by piyushchauhan2011** [comment]
A lot of people don't like `node-sass` because of re-compilation when switching between node versions and also long native compilation when embedded in docker. Would be nice to have `dart-sass` support in next-sass

**Comment by timneutkens** [comment]
I'm going to close this in favor of https://github.com/zeit/next.js/issues/8626

Thanks for your contribution 🙏
