### ISSUE TITLE
Is there any reason I will need to keep using this plugin in next v9?

### ISSUE THREAD

**Issue by avivash** [zeit/next-plugins#489]
Since `next` v9 ships with full TS support, I'm wondering if there's any reason I shouldn't remove this plugin from my app?

**Comment by kachkaev** [comment]
TypeScript plugin can be removed from the app, yes. Details are in the [upgrading instructions](https://github.com/zeit/next.js/blob/canary/UPGRADING.md#migrating-from-v8-to-v9).

**Comment by avivash** [comment]
thanks!
