### ISSUE TITLE
@zeit/next-typescript Not up to date on npm install

### ISSUE THREAD

**Issue by zachariahtimothy** [zeit/next-plugins#49]
I am wanting to use (TS Transform Graphql)[https://github.com/firede/ts-transform-graphql-tag] with the @zeit/next-typescript package. When I install the @zeit/next-typescript package the plugin is not initialized. When I look at the node_modules/@zeit/next-typescript/index.js file I find line 31 contains 
```
options: {
   transpileOnly: true
}
```
Instead of:
```
options: Object.assign({}, {
   transpileOnly: true
}, nextConfig.typescriptLoaderOptions)
```
Would it be possible to re-release to take advantage of the typescriptLoaderOptions option?

Note I am using yarn and did a full cache clean and re-install with no fix. Using "@zeit/next-typescript": "^0.0.9"

**Comment by timneutkens** [comment]
It's not released yet.

**Comment by zachariahtimothy** [comment]
Awesome thank you @timneutkens !

**Comment by timneutkens** [comment]
Released a new version.
