### ISSUE TITLE
camelCase support for cssLoaderOptions

### ISSUE THREAD

**Issue by sahalsajjad** [zeit/next-plugins#51]
@thekevinscott  has done a wonderful job with pull request #16 

However, there doesn't seem to be support for camelCase option of css-loader.
Would support for this be added soon?

### Problem:
Everything works fine for one-worded classnames like 'navbar', 'column', 'sticky' etc. However, for class names like 'navbar-bg', 'column-12', 'sticky-top' has an empty string. (ie *class* in the HTML instead of something like *class="23Tbhqewpe_54Yu"* 

### Expected behaviour:
classnames like navbar-bg gets transformed to navbarBg (or their hashes) 

I am a newbie, so could you help me with any other workaround to camelCasing for legacy css (for eg: foundation framework)?

**Comment by timneutkens** [comment]
It's not released yet.

**Comment by sahalsajjad** [comment]
@timneutkens Thanks for letting me know.
Do you have a rough estimate of the date for next release ? :smiley:
