### ISSUE TITLE
A big chunk of styles from .scss file is being stripped upon build

### ISSUE THREAD

**Issue by githubdoramon** [zeit/next-plugins#514]
When running on dev, I can see all my styes in the styles.chunk.css file, but when building the app, 80% of the file is stripped and I have no idea why.

Any hints on what am I doing wrong?

This is the next.config.js

`
const withSass = require('@zeit/next-sass');
const withTM = require('next-transpile-modules');

const {
  WebpackBundleSizeAnalyzerPlugin
} = require('webpack-bundle-size-analyzer');
const { ANALYZE } = process.env;

module.exports = withSass(
  withTM({
    transpileModules: ['@amy/components'],
    webpack(config, options) {
      if (ANALYZE)
        config.plugins.push(new WebpackBundleSizeAnalyzerPlugin('stats.txt'));

      return config;
    },
    publicRuntimeConfig: {
      system: 'studio'
    }
  })
);
`

**Comment by githubdoramon** [comment]
Was being stupid.. sorry

**Comment by timneutkens** [comment]
So I guess this can be closed.
