### ISSUE TITLE
@zeit/next-bundle-analyzer causes npm audit error 

### ISSUE THREAD

**Issue by steida** [zeit/next-plugins#516]
> Remediation
> Upgrade webpack-bundle-analyzer to version 3.3.2 or later. For example:
> 
> webpack-bundle-analyzer@^3.3.2:
> 
>   version "3.3.2"

Last version is 3.4.1

**Comment by timneutkens** [comment]
See https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer#nextjs--webpack-bundle-analyzer

**Comment by steida** [comment]
Ups.
