### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by mulholio** [zeit/next-plugins#524]
I went to make a PR for next-css to upgrade dependencies but there doesn't seem to be any activity on this repo and several PRs have been left open with no comment. Is making a PR here the right place to contribute?

next-css on NPM lists version `1.0.1` whereas this repo is only on `0.2.1-canary.4`. Are packages being published elsewhere that we can't see?

If this repo is still active, could we get a `contributing.md` added to encourage more open source contributions?

@rauchg @timneutkens

**Comment by timneutkens** [comment]
The plan is to move most plugins to github.com/zeit/next.js, however some will be added into core like next-css.

**Comment by mulholio** [comment]
Thanks for such a speedy response!

Does this mean best to hold off on changes here? Do you have a rough timeline on when this will come into play? Are they any issues we can help out with to speed this along?

**Comment by timneutkens** [comment]
Yeah I've been holding off on changes here based on those future plans, I'm not sharing a timeline as we'd be asked for it every other day, but soon, there's currently no particular issues on this repo, the Next.js repo has quite a few good first issue / help wanted labeled issues!

**Comment by jkjustjoshing** [comment]
@timneutkens if I want to submit a feature request/bug report, or a PR, what should I do? Will open issues/PRs in this repo be migrated to the [main repo](https://github.com/zeit/next.js)?
