### ISSUE TITLE
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.  - options has an unknown property 'minimize'. These properties are valid:

### ISSUE THREAD

**Issue by tmohammad78** [zeit/next-plugins#541]
I did correct by document and I import ./style.scss file in my js file 
but i have this error  i asked in stackoverflow but i dont get answer
please help me to fix it

package.json
dependencies{
    "@zeit/next-sass": "^1.0.1",
    "next": "^9.0.6",
    "node-sass": "^4.12.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
}

next.config.js
```
const withSass = require('@zeit/next-sass')
module.exports = withSass({
  /* config options here */
})
```
![Screenshot (247)](https://user-images.githubusercontent.com/36788573/65492086-30c65400-debd-11e9-9c54-a000558fbb2c.png)
![Screenshot (248)](https://user-images.githubusercontent.com/36788573/65492087-30c65400-debd-11e9-9481-5335444db2a4.png)
![Screenshot (246)](https://user-images.githubusercontent.com/36788573/65492089-315eea80-debd-11e9-9cab-ebf70295ac3e.png)

**Comment by arunpdl** [comment]
This issue seems to occur in css-loader 2.0 and above. Try downgrading it to lower versions. 
Or, you can use this [workaround](https://github.com/zeit/next-plugins/issues/392#issuecomment-475845330).

**Comment by arronhunt** [comment]
Confirmed, this is a pretty annoying issue. I have a brand new Next project and am getting this error. 

thanks for the hack @arunpdl

**Comment by T1263** [comment]
I came across this issue as well.

adding both  @zeit/next-css and @zeit/next-sass
to my project then 

in next.config.js : 

`const withCSS = require("@zeit/next-css");`
`const withSass = require("@zeit/next-sass");`
`module.exports = withCSS({});`
`module.exports = withSass({});`

These seems to fix the issue for now.

**Comment by nahtnam** [comment]
Same issue, I would recommend doing what @arunpdl mentioned

**Comment by Yaolegol** [comment]
In my case, the solution was (thanks arunpdl)

```
// next.config.js
const **withSass** = require('@zeit/next-**sass**');

function HACK_removeMinimizeOptionFromCssLoaders(config) {
  console.warn(
    'HACK: Removing `minimize` option from `css-loader` entries in Webpack config',
  );
  config.module.rules.forEach(rule => {
    if (Array.isArray(rule.use)) {
      rule.use.forEach(u => {
        if (u.loader === 'css-loader' && u.options) {
          delete u.options.minimize;
        }
      });
    }
  });
}

module.exports = **withSass**({
  webpack(config) {
    HACK_removeMinimizeOptionFromCssLoaders(config);
    return config;
  },
});
```

**Comment by glauberm** [comment]
@Yaolegol solution works for me. Anybody has any idea what might be causing this error?

**Comment by andreisocaciu** [comment]
Does anybody know when will this be fixed?

**Comment by rlech** [comment]
same issue here but the fix is not working. I am trying to use semantic ui react with next.js

**Comment by Calderis** [comment]
I was locked few minutes ago with my previous package.json with the same problem. Compilation did not pass on now.sh which was quite a problem.
```
"dependencies": {
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "next": "^9.0.2",
    "node-sass": "^4.12.0"
	...
  }
```
I change for : (removing *^* in order to lock my packages without buggy versions.)
```
"dependencies": {
    "@zeit/next-css": "1.0.1",
    "@zeit/next-sass": "1.0.1",
    "next": "9.0.2",
    "node-sass": "4.12.0"
	...
  }
```
I'll set them back once the PR will be merge. It's not the best solution but at least it compiles.

The *^* symbol does install the specified version of the package or above, by removing it you will install the exact version you want to.

Hope it'll helps someone 🙄

**Comment by Timer** [comment]
Please try `next@v9.0.8-canary.3` -- this version should fix these broken plugins.

**Comment by powderham** [comment]
I got this to work using :

`next@9.0.8-canary.4 `

and

```
const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");
module.exports = withCSS(
  withSass({
    /* config options here */
  })
);
```

**Comment by naveenkash** [comment]
where's the solution for this bug i saw tutorial on youtube they use the smae code but there code is working fine how is that

**Comment by saliljnr** [comment]
> I got this to work using :
> 
> `next@9.0.8-canary.4 `
> 
> and
> 
> ```
> const withSass = require("@zeit/next-sass");
> const withCSS = require("@zeit/next-css");
> module.exports = withCSS(
>   withSass({
>     /* config options here */
>   })
> );
> ```
This is the only solution that worked for me so far... next@9.0.7

**Comment by tan-ahmed** [comment]
I am facing this issue too

**Comment by Timer** [comment]
Please upgrade to the latest `next@canary` which should fix all known variants of CSS issues.

**Comment by luvletterldl** [comment]
if you need css and stylus,you can update your next.config.js like this:`// next.config.js
const withCSS = require('@zeit/next-css');

function HACK_removeMinimizeOptionFromCssLoaders(config) {
  console.warn(
    'HACK: Removing `minimize` option from `css-loader` entries in Webpack config',
  );
  config.module.rules.forEach(rule => {
    if (Array.isArray(rule.use)) {
      rule.use.forEach(u => {
        if (u.loader === 'css-loader' && u.options) {
          delete u.options.minimize;
        }
      });
    }
  });
}

module.exports = withCSS({
  webpack(config) {
    HACK_removeMinimizeOptionFromCssLoaders(config);
    return config;
  },
});
`

**Comment by MathieuLoutre** [comment]
Just reporting that I'm having this issue on 9.1.2 with `@zeit/next-stylus` @Timer.  I've used @luvletterldl's workaround for now. Anything I can help with maybe?

**Comment by Manikjhamb** [comment]
> > I got this to work using :
> > `next@9.0.8-canary.4 `
> > and
> > ```
> > const withSass = require("@zeit/next-sass");
> > const withCSS = require("@zeit/next-css");
> > module.exports = withCSS(
> >   withSass({
> >     /* config options here */
> >   })
> > );
> > ```
> 
> This is the only solution that worked for me so far... next@9.0.8_canary.5
I think . it is next@9.0.8-canary.5 .  ... typo :)

**Comment by dan-cooke** [comment]
We are seeing this issue on next 9.2.1 still

**Comment by satyamurthy515** [comment]
Hi,

Even I got this same error. To resolve this I deleted my **Node_modules** and **package-lock.json** and installed modules again with **npm i**.  And it resolved for me.

**Comment by MarkLyck** [comment]
Having this problem on `next@9.5.3` and `"@zeit/next-css": "^1.0.1",` doesn't seem like it has been permanently fixed yet.

Implementing workarounds suggested.

**Comment by 7iomka** [comment]
save issue with latest canary version

**Comment by danvoyce** [comment]
Getting this issue in 9.5.4

**Comment by jooj123** [comment]
This should be re-opened - seems to have been reintroduced on next@^10
