### ISSUE TITLE
next-preact plugin still needs updating

### ISSUE THREAD

**Issue by kennykimjr** [zeit/next-plugins#554]
ref: https://github.com/zeit/next-plugins/pull/544

When you pull from latest, you still get the version of this plugin from 6 months ago. The current version needs to have its version bumped and updated on the NPM registry. Also if I'm not mistaken, this latest change will still require the use of React and React-dom for building even though it's not used in the actual building in the app due to the resolve checks internally in NextJS. Also that this will not work with NextJS version 9.

**Comment by npeham** [comment]
Same here. @kennykimjr Do you have a workaround for it?

**Comment by kennykimjr** [comment]
@npeham The only workaround is to wait for a contributor liker @Timer to increment the version in package.json and then have whoever has publish access on NPM to update it on the registry. Otherwise, you can probably just copy-paste the code from the repo to your project.

**Comment by Timer** [comment]
Hey! We're currently not planning on releasing a new version of this plugin. We're working on a new plugin system that'll replace all the existing plugins. 😄 

For now, we've merged the PR so users can copy the example into their own project.
