### ISSUE TITLE
@next/bundle-analyzer won't generate analyze html files in next.conf.ts (typescript)

### ISSUE THREAD

**Issue by sagartalla** [zeit/next-plugins#555]
Steps: 
1) create [with-typescipt](https://github.com/zeit/next.js/tree/canary/examples/with-typescript) example
2) add next.config.ts
3) add @next/bundle-analyze plugin

Reproduction: https://github.com/sagartalla/next-bundle-analyzer-typescript.

**Comment by kachkaev** [comment]
next.config.ts is not supported, see https://github.com/zeit/next.js/issues/5318

2maintainers: how about checking for this file at startup and throwing an error when it exists, while next.config.js does not?

**Comment by timneutkens** [comment]
@kachkaev feel free to PR that. I'll close this issue as it's answered.
