### ISSUE TITLE
Trouble with order of styles in output file

### ISSUE THREAD

**Issue by JerryCauser** [zeit/next-plugins#59]
I'm not sure should that trouble be here or in `nextjs` rep, but lets start from here and if will be need ed - move this.

Let's start:
In simple way we have file like that:
```jsx
import React, {Component} from 'react'
import '/styles/base.scss'
import css from './Wrapper.scss'
import Head from 'next/head'

export function withWrapper(Child) {
  class Wrapper extends Component {
    static async getInitialProps(...args){
      if (typeof Child.getInitialProps !== 'function') {
        return {}
      }
      let initialProps = Child.getInitialProps(...args)
      if (initialProps instanceof Promise) {
        initialProps = await initialProps
      }
      return initialProps
    }
    
    render() {
      return <div className={css.main}>
        <Head>
          <link rel="stylesheet" href="/_next/static/style.css"/>
        </Head>
        <Header/>
        <div className={css.container}>
          <Child {...this.props}/>
        </div>
      </div>
    }
  }
  return Wrapper
}

export default withWrapper
```

I expect styles in file `styles/base.css` will be at the top of `style.css`. Bcs it's my vendor.
But now styles of `Wrapper.scss` are at the top of the file `style.css`. Even more, all the styles that are in the `Child` component will get to the top of the file.

Looks like calling of components starts from the deepest one and all of styles adds with a `push`, so in the end we got: styles of deepest child will be at top of `styles.css` and style, what we expect to see at the top (vendor, normalize, etc...) appears at the bottom of file....

![image](https://user-images.githubusercontent.com/5141037/36318799-ffe9bd00-1351-11e8-85b1-6940ca69f5e0.png)

For myself I hacked it with spliting code in two files: vendor and app, but I think it is not the good way to solve that trouble.

**Comment by timneutkens** [comment]
Looks related: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/200

**Comment by JerryCauser** [comment]
Yeah, it is.
