### ISSUE TITLE
[next-css] Sourcemaps broken when using postcss

### ISSUE THREAD

**Issue by cullylarson** [zeit/next-plugins#596]
I'm using next-css and postcss together. Works great, except sourcemaps don't work. They're generated, but they don't point to the correct location in the source files. I created a repo that demonstrates the issue: https://github.com/cullylarson/next-css-postcss-sourcemap-issue

In the repo, you'll see a CSS file like (body.css):

```css
html {
    font-size: 100%;
}

body {
    border: 3px solid red;
}
```

If you start the server, open dev tools, and inspect the `<body>` element, it will tell you that the body select is on line 1 of `body.css`. If you click on that, you'll be brought to the `html` selector. Though the `body.css` file in dev tools is correct (so at least the source code is preserved in the map, just not the correct line numbers).

Here are a few pertinent files, or you can check out the repo:

## next.config.js

```js
const withCSS = require('@zeit/next-css')

module.exports = withCSS({})
```

## .babelrc

```json
{
    "presets": [
        ["next/babel", {
            "preset-env": {},
            "styled-jsx": {
              "plugins": ["styled-jsx-plugin-postcss"]
            }
        }]
    ]
}
```

## postcss.config.js

```js
const path = require('path')
const createResolver = require('postcss-import-webpack-resolver')

module.exports = ctx => ({
    map: true,
    plugins: {
        'postcss-import': {
            resolve: createResolver({
                alias: {
                    '@css': path.resolve(__dirname, 'client/style'),
                    '@client': path.resolve(__dirname, 'client'),
                },
            }),
        },
        'postcss-rem': {
            baseline: 16,
            fallback: false,
            precision: 5,
        },
        'postcss-mixins': {},
        'postcss-simple-vars': {},
        'postcss-nested-ancestors': {},
        'postcss-nested': {},
        'postcss-custom-media': {},
        'postcss-calc': {mediaQueries: true},
        'postcss-preset-env': {
            stage: 0,
            browsers: 'last 2 versions',
        },
        'cssnano': {
            zindex: false,
            // autoprefixer is included in postcss-preset-env, so no need to do it again in nano
            autoprefixer: false,
            discardComments: {removeAll: true}
        },
        'postcss-reporter': {clearReportedMessages: true},
    }
})
```

**Comment by Temkit** [comment]
what is your nextjs version ?

**Comment by timneutkens** [comment]
Can you try built-in CSS support?

**Comment by cullylarson** [comment]
@timneutkens I didn't know that existed. Anyway, I got rid of `next-css` and am apparently using build-in css support. Seems to work great; sourcemaps are reporting correctly. Though for some reason I can no longer export a function from `postcss.config.js` (it's not allowed in Next.js 9.2). Not sure why that is. Anyway, I guess this is resolved in that `next-css` is no longer necessary :)

**Comment by timneutkens** [comment]
@cullylarson It was released yesterday 🚀
