### ISSUE TITLE
Where to properly place withCSS function in config file?

### ISSUE THREAD

**Issue by danboyle8637** [zeit/next-plugins#597]
In my next.config.js file, I have some env variables set.

```
module.exports = {
   env: {...}
}
```

I am trying to get prismjs to work properly and it seems to when I use the next-css plugin but I don't know where to actually put the withCSS function.

I'm looking at what the default config takes:
https://github.com/zeit/next.js/blob/canary/packages/next/next-server/server/config.ts#L12-L63

Where should this function go when you have multiple settings in the config file?

**Comment by timneutkens** [comment]
You no longer need next-css to use CSS imports: https://nextjs.org/blog/next-9-2#built-in-css-support-for-global-stylesheets

**Comment by kachkaev** [comment]
@timneutkens 🎉
Might be worth closing https://github.com/zeit/next.js/issues/8626#issuecomment-568910859 as it looks like the right time now 😉
