### ISSUE TITLE
CSS HMR not working with 'extracted-loader'

### ISSUE THREAD

**Issue by JerryCauser** [zeit/next-plugins#62]
I don't know why, but in `@zeit/next-sass` not working HMR. I tried to fix and swap `extracted-loader` with `css-hot-loader` and it's working for me. 

Is hmr working now or not?

next@5.0.0 (also tested in 5.0.1-canary.2)

my next-config
```javascript
const webpack = require('webpack')
const withSass = require('@zeit/next-sass')

module.exports = withSass({
  cssLoaderOptions: {
    modules: true,
    localIdentName: '[local]-[hash:base64:5]',
    sourceMap: false
  },
  sassLoaderOptions: {
    sourceMap: false,
    includePaths: ["./", "./styles/base"]
  },
  webpack(config) {
    const providePlugin = new webpack.ProvidePlugin({
      'fetch': 'isomorphic-unfetch',
      'React': 'react'
    })
    config.plugins.push(providePlugin)
    return config
  }
})
```

**Comment by JerryCauser** [comment]
I found the reason: [extracted-loader: ^1.0.4](https://github.com/zeit/next-plugins/blob/8a9f5a89c835e2c4c18398521a361d95c0d80f40/packages/next-css/package.json#L10)
For some reasons I locked in my package.json extracted-loader at version 1.0.4
With that version HMR isn't working. Need to update to ^1.0.6
@alexan, check your deps

**Comment by alexan** [comment]
thanks that also seems to have fixed my issues
