### ISSUE TITLE
i don't want the extracted css file when using '@zeit/next-less'

### ISSUE THREAD

**Issue by lei3536** [zeit/next-plugins#633]
After build , my css codes were generated in a [hash].css file.
So, i get Html code with some code look like `link rel="stylesheet" href="/imagegenerator/_next/static/css/styles.02bea7e5.chunk.css" `.
But, I want the HTML code look like "<style>.myClass{color: red}</style>"
How do?

there is my 'next.config.js'
`
const withLess = require('@zeit/next-less');
const path = require('path');

let config = {
  distDir: '__next',
  assetPrefix: '/imagegenerator',
  webpack: (conf) => {
    conf.module.rules.push(
      {
        test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
        use: {
          loader: 'url-loader',
          options: {
            limit: 100000,
            name: '[name].[ext]',
          },
        },
      },
    );
    Object.assign(conf.resolve, {
      alias: {
        ...conf.resolve.alias,
        '@': path.resolve(__dirname, 'src'),
        '@components': path.resolve(__dirname, 'src/components'),
        '@lib': path.resolve(__dirname, 'src/lib'),
        '@util': path.resolve(__dirname, 'src/util'),
        '@config': path.resolve(__dirname, 'src/config'),
        '@pages': path.resolve(__dirname, 'pages'),
      },
    });

    return conf;
  },
};

config = withLess(config);
module.exports = config;

`

**Comment by yangzhennupt** [comment]
I have same question, have you solvde this problem?

**Comment by lei3536** [comment]
> I have same question, have you solvded this problem?

copy the source code ,and change the webpack config

**Comment by yangzhennupt** [comment]
@lei3536   can you share your code ? I have this problem which confused me two days

**Comment by lei3536** [comment]
@yangzhennupt 
https://github.com/lei3536/my-withLess
