### ISSUE TITLE
@zeit/next-bundle-analyzer vulnerability

### ISSUE THREAD

**Issue by vitaliemiron** [zeit/next-plugins#640]
npm reports security vulnerability, can you update please? 

<img width="745" alt="Screen Shot 2020-05-18 at 13 21 16" src="https://user-images.githubusercontent.com/45145592/82202367-77fccb80-990a-11ea-97bd-ec3f6736bc7c.png">

**Comment by timneutkens** [comment]
See https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer
