### ISSUE TITLE
[@zeit/next-typescript] doesn't seem to load nested typescript files

### ISSUE THREAD

**Issue by derekr** [zeit/next-plugins#66]
Def not an urgent bug or request, but would be chill to support page directories. Might even be a simple config I'm missing as well.

```
pages/
  /index
    index.tsx
```

Will yield a 404

```
pages/
   /index.tsx
```

Works as expected. I'd expect nested page directories to work the same.

**Comment by timneutkens** [comment]
@derekr try upgrading to `next@canary` + latest @zeit/next-typescript and let me know if it's any better.

**Comment by timneutkens** [comment]
@derekr do you have an update? Thanks 🙏

**Comment by derekr** [comment]
Verified! Thanks for the tip.

**Comment by timneutkens** [comment]
Great, i guess the change i Made to how we load pages in development helped solving this issue 👍🏻
