### ISSUE TITLE
[next-css] unable to access to static file

### ISSUE THREAD

**Issue by ZhengYuTay** [zeit/next-plugins#67]
Repo link [https://github.com/ZhengYuTay/next-redux-withcss-jest](url)

`<link rel="stylesheet" href="/_next/static/style.css" />` is present in _document.js

but unable to it's not able to be accessed.

**Comment by bryandowning** [comment]
The link to your repo is private, but this may have been fixed already in a newer alpha version of next js. See: https://github.com/zeit/next.js/issues/3712

**Comment by timneutkens** [comment]
https://github.com/ZhengYuTay/next-redux-withcss-jest

**Comment by timneutkens** [comment]
This is actually fixed in another issue though, the directory was not applied correctly. try upgrading to next@canary.
