### ISSUE TITLE
Combining CSS, SASS and LESS configuration.

### ISSUE THREAD

**Issue by sfernandezsl** [zeit/next-plugins#69]
There is a way to work combining more than one styles configuration?
I noticed when I try to combine two preprocesor, the last one overwrite the output file.

I want to add https://ant.design/ LESS files as a global style and manage my app styles using SASS with CSS Modules.

Can you show me an example if there is a way to do it?

**Comment by JerryCauser** [comment]
@sfernandezsl, https://github.com/zeit/next-plugins/issues/71#issuecomment-367421555

**Comment by sfernandezsl** [comment]
thanks @JerryCauser it works! just one more thing...
It is possible to set up css Modules just in one of the styles configurations?
have CSS as global styles and SASS with CSS Modules?

**Comment by JerryCauser** [comment]
just wrap your global styles in `:global{}`
Also, you can split your CSS file and make 2 files `vendor.css` for ant-design less files and 'app.css' for sass project files. When #55 will be merged, then it gives you the possibility to split files by using `include` or `exclude`.
