### ISSUE TITLE
Provide next-stylus

### ISSUE THREAD

**Issue by breeswish** [zeit/next-plugins#72]
[stylus](http://stylus-lang.com/) is also a popular and advanced preprocessor. Would like to see it natively supported : )

**Comment by timneutkens** [comment]
Can be created as external plugin, feel free to base it on next-sass.

**Comment by phaistonian** [comment]
@timneutkens  I am afraid that's not so simple. 

For some reason(s) this does not work. I am almost sure this is related to how stylus-loader works sine, as I noticed, sass-loader provides some extra options that are probably needed in stylus case as well.

If you have some time to investigate and provide some pointers, that would have been great.

Thank you.

**Comment by weotch** [comment]
It looks like this was started here: https://github.com/romuloalves/next-plugins/tree/next-stylus
