### ISSUE TITLE
next-bundle-analyzer usage unclear

### ISSUE THREAD

**Issue by jthegedus** [zeit/next-plugins#75]
The https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer#usage-with-environment-variables usage example references a `yarn build` script but does not describe the script. Is it simply `next build`? I've tried a few combinations of this and not been able to get any of the analyze results to show in a browser.

PS. I'm happy to PR an update to the docs, I just cannot before understanding it myself :sweat_smile:

**Comment by timneutkens** [comment]
yeah it's just next build. nothing special there

**Comment by jthegedus** [comment]
Well, I was going to take another look at my failing example but it now works. No idea how I screwed it up last time :man_shrugging: Thanks for the info.
