### ISSUE TITLE
TypeScript not recognizing Sass modules

### ISSUE THREAD

**Issue by fandy** [zeit/next-plugins#91]
I have Sass Modules setup and am currently importing my styles like this: `import s from '../styles/style.scss'`

**next.config.js**
```
const withTypescript = require('@zeit/next-typescript')
const withSass = require('@zeit/next-sass')
module.exports = withTypescript(withSass({
  cssModules: true,
  cssLoaderOptions: {
    importLoaders: 1,
    localIdentName: '[local]__[hash:base64:5]'
  },
  sassLoaderOptions: {
    includePaths: ['styles']
  }
}))
```

TS (at least in VScode) is complaining that `[ts] Cannot find module '../styles/style.scss'.`, but the Sass file is imported find and I can see it reflected in the browser. How can I get TS to recognize the file?

![image](https://user-images.githubusercontent.com/19108762/37249908-adbdb0ee-24be-11e8-903d-8890443d3b93.png)

**Comment by fandy** [comment]
I fixed it by adding this to `typings/declarations.d.ts`

```
declare module '*.scss' {
  const content: {[className: string]: string};
  export = content;
}

```

**Comment by mohammedzamakhan** [comment]
I did this step, and I no longer see the error, and my page loads normally, and I do see the class applied to the element, but the styles did not apply because they were not included on the page!!

**Comment by ritz078** [comment]
@mohammedzamakhan was your problem fixed?

**Comment by drudv** [comment]
I have `An export assignment cannot be used in a module with other exported elements.ts(2309)` error on `export = content` line. Does anyone have any ideas how to overcome this?

**Comment by JiangLiruii** [comment]
> I have `An export assignment cannot be used in a module with other exported elements.ts(2309)` error on `export = content` line. Does anyone have any ideas how to overcome this?

you can change the `export = content` to `export default content`, 
or you can just use
```js
declare module '*.scss' {
  export const content: {[className: string]: string};
}
```

**Comment by aequasi** [comment]
Or even
```typescript
declare module '*.scss' {
    const content: { [className: string]: string };
    export default content;
}

```

**Comment by eden-lane** [comment]
![image](https://user-images.githubusercontent.com/2963477/71779801-d44df700-2fca-11ea-9ca0-750a060dd388.png)

**Comment by matijamrkaic** [comment]
The file can also go in root as `typings.d.ts`.

**Comment by hars1130** [comment]
> I fixed it by adding this to `typings/declarations.d.ts`
> 
> ```
> declare module '*.scss' {
>   const content: {[className: string]: string};
>   export = content;
> }
> ```

declare module '*.scss' module makes it applicable globally. Can I make the module applicable only to .scss files in particular directory ie' something like './myFile.scss'??

**Comment by rphelan** [comment]
I also added `readonly` to prevent accidental assignment:
```typescript
declare module '*.scss' {
  const content: { readonly [className: string]: string };
  export default content;
}
```
