### ISSUE TITLE
Sass imports not working for folders

### ISSUE THREAD

**Issue by fandy** [zeit/next-plugins#92]
I'm trying to import an entire folder of mixins like so:

```
@import "foundation/*"
```

```
styles
--/style.scss
--/foundation/
--/--/_colors.scss
--/--/_typography.scss
```

Importing the individual files like `@import "foundation/_colors"` works, but I'm unable to import the folder using wildcards.

**Comment by timneutkens** [comment]
Unrelated to next-sass, since next-sass just implements sass-loader. Please file an issue there (if there isn't one already)
