### ISSUE TITLE
Hydration error in Emotion example

### ISSUE THREAD

**Issue by fandy** [zeit/next-plugins#93]
The Emotion example is throwing this error in dev:

`Warning: Expected server HTML to contain a matching <div> in <div>.`

I did a bit of research and found it had something to do with the [styles unable to be hydrated](https://stackoverflow.com/questions/45350360/react-16-warning-warning-js36-warning-did-not-expect-server-html-to-contain-a?noredirect=1&lq=1), but I still do not fully understand. Can anyone provide an explanation?

**Comment by timneutkens** [comment]
Unrelated to next-plugins. You already made an issue on next.js afaik.
